export type EssayMedia = { slug: string; afterSection: string; title: string; src: string; alt: string; caption: string; sourceUrl: string; sourceLabel: string; width: number; height: number; credit: string };

export const essayMedia: readonly EssayMedia[] = [
  {
    "slug": "frankenstein-ai",
    "afterSection": "scene-3",
    "title": "닮은 모습에서 설계의 책임까지",
    "src": "/images/essays/frankenstein-ai/concept.svg",
    "alt": "외양, 대화, 책임을 서로 다른 세 층으로 그린 개념도",
    "caption": "닮은 외양과 대답하는 동작을 보았을 때 생기는 기대, 그리고 사용 조건과 책임을 정하는 일을 구분한 편집 개념도입니다.",
    "sourceUrl": "https://www.gutenberg.org/cache/epub/42324/pg42324-images.html",
    "sourceLabel": "Mary Shelley · Frankenstein, 1831년판",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "eratosthenes",
    "afterSection": "scene-3",
    "title": "그림자와 중심각의 연결",
    "src": "/images/essays/eratosthenes/concept.svg",
    "alt": "평행한 햇빛, 구형 지구의 두 지점과 중심각을 연결한 개념도",
    "caption": "평행한 햇빛과 구형 지구를 가정하면 두 지점의 막대기 각도 차이를 지구의 중심각과 연결할 수 있습니다. 도시의 실제 배치나 거리를 재현한 지도는 아닙니다.",
    "sourceUrl": "https://mathshistory.st-andrews.ac.uk/Biographies/Eratosthenes/",
    "sourceLabel": "세인트앤드루스대학교 MacTutor: Eratosthenes",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "calendar",
    "afterSection": "scene-2",
    "title": "그레고리력의 윤년 판단",
    "src": "/images/essays/calendar/concept.svg",
    "alt": "4, 100, 400의 배수 조건으로 그레고리력 윤년을 판단하는 흐름도",
    "caption": "4의 배수인 해에서 100의 배수는 제외하되 400의 배수는 다시 윤년으로 삼는 규칙입니다. 다른 달력의 윤년 규칙을 나타내지는 않습니다.",
    "sourceUrl": "https://aa.usno.navy.mil/faq/calendars",
    "sourceLabel": "미 해군 천문대: Introduction to Calendars",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "longitude",
    "afterSection": "scene-2",
    "title": "두 시각 사이에 남는 경도",
    "src": "/images/essays/longitude/concept.svg",
    "alt": "현지 정오와 기준 시각 11시를 비교해 한 시간과 15도를 연결한 계산 예시",
    "caption": "지구의 하루 회전을 24시간으로 나누면 태양 기준 시각 차이 한 시간은 경도 차이 15도에 대응합니다. 그림은 원고의 계산을 단순화한 예시입니다.",
    "sourceUrl": "https://www.rmg.co.uk/stories/time/what-longitude",
    "sourceLabel": "왕립 그리니치 박물관: What is longitude?",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "maps",
    "afterSection": "scene-2",
    "title": "투영이 바꾸는 격자의 간격",
    "src": "/images/essays/maps/concept.svg",
    "alt": "위도가 높아질수록 세로 간격이 늘어나는 메르카토르 격자의 개념도",
    "caption": "메르카토르 투영에서는 고위도로 갈수록 면적이 크게 표현됩니다. 이 격자는 보존 성질을 설명하기 위한 개념도이며 실제 세계지도나 축척 자료가 아닙니다.",
    "sourceUrl": "https://doc.esri.com/en/arcgis-pro/latest/help/mapping/properties/mercator.html",
    "sourceLabel": "Esri 공식 문서: Mercator",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "relativity",
    "afterSection": "scene-5",
    "title": "높이 실험과 운동 실험 구분",
    "src": "/images/essays/relativity/concept.svg",
    "alt": "높이가 다른 시계 비교와 이온 운동 비교를 별도 패널로 나눈 개념도",
    "caption": "원고가 소개하는 NIST의 높이 차이 비교와 이온 운동 비교는 서로 다른 실험입니다. 이 그림은 두 조건을 나눠 보여 주며 실험 장치나 측정값을 재현하지 않습니다.",
    "sourceUrl": "https://www.nist.gov/news-events/news/2010/09/nist-pair-aluminum-atomic-clocks-reveal-einsteins-relativity-personal-scale",
    "sourceLabel": "NIST: Atomic clocks and relativity at a personal scale",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "telescope",
    "afterSection": "scene-1",
    "title": "한 밤의 점에서 여러 밤의 기록으로",
    "src": "/images/essays/telescope/concept.svg",
    "alt": "목성 주변 점의 서로 다른 배치를 네 줄의 관측 기록 예시로 비교한 그림",
    "caption": "밝은 점의 위치를 여러 밤에 걸쳐 비교하면 한 장면만으로는 얻기 어려운 질문이 생깁니다. 점의 배치는 설명용으로 새로 그렸으며 갈릴레오의 실제 관측 기록이 아닙니다.",
    "sourceUrl": "https://www.gutenberg.org/cache/epub/46036/pg46036-images.html",
    "sourceLabel": "갈릴레오: The Sidereal Messenger, E. S. Carlos 영어 번역",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "microscope",
    "afterSection": "scene-2",
    "title": "코르크에서 보이는 작은 칸",
    "src": "/images/essays/microscope/concept.svg",
    "alt": "코르크의 칸을 확대해 벽과 빈 공간을 구분한 설명용 그림",
    "caption": "후크가 코르크에서 묘사한 작은 칸을 떠올리기 위한 편집 개념도입니다. 실제 표본 사진이나 후크의 도판을 복제하지 않았으며 보이는 구조만으로 기능이 정해지지는 않습니다.",
    "sourceUrl": "https://www.gutenberg.org/cache/epub/15491/pg15491-images.html",
    "sourceLabel": "로버트 후크: Micrographia, 1665년 원문 전사본",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "evolution",
    "afterSection": "scene-2",
    "title": "사다리가 아닌 갈림길",
    "src": "/images/essays/evolution/concept.svg",
    "alt": "공통조상에서 갈라진 가지와 나란한 현재의 가지 끝을 보여 주는 계통 개념도",
    "caption": "공통조상에서 여러 계통이 갈라지는 모습을 그렸습니다. 가지 끝의 위치는 우열을 뜻하지 않으며 특정 종의 실제 계통도나 분기 연대를 나타내지 않습니다.",
    "sourceUrl": "https://darwin-online.org.uk/content/contentblock?itemID=F373&basepage=1&hitpage=1&viewtype=text",
    "sourceLabel": "다윈, 『종의 기원』 초판, 1859",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "mendel",
    "afterSection": "scene-3",
    "title": "네 칸은 확률을 정리한다",
    "src": "/images/essays/mendel/concept.svg",
    "alt": "Aa와 Aa의 교배에서 AA, Aa, Aa, aa 조합을 정리한 네 칸 확률표",
    "caption": "Aa인 부모 둘을 가정한 단순 교배의 조합입니다. 같은 조합 확률을 네 칸에 적은 것이며 실제 자손 네 개마다 일정한 결과가 나온다는 뜻은 아닙니다.",
    "sourceUrl": "https://openstax.org/books/biology-2e/pages/12-1-mendels-experiments-and-the-laws-of-probability",
    "sourceLabel": "OpenStax Biology 2e, 멘델의 실험과 확률",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "periodic-table",
    "afterSection": "scene-2",
    "title": "빈칸이 만드는 검증의 자리",
    "src": "/images/essays/periodic-table/concept.svg",
    "alt": "분류표의 빈칸에서 예측 성질과 새 관찰을 비교하는 과정",
    "caption": "분류에 남긴 빈칸은 예상 성질을 적고 새로운 관찰과 비교할 자리가 됩니다. 이 표는 멘델레예프의 실제 주기율표를 복제한 것이 아니라 원고의 논리를 정리한 개념도입니다.",
    "sourceUrl": "https://periodic-table.rsc.org/history/about",
    "sourceLabel": "왕립화학회, 주기율표의 발전",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "entropy",
    "afterSection": "scene-2",
    "title": "기체가 갈 수 있는 공간",
    "src": "/images/essays/entropy/concept.svg",
    "alt": "기체가 한쪽 공간에 있던 상태와 분리판 제거 후 넓은 공간의 배치를 비교한 그림",
    "caption": "분리판을 제거하면 기체가 접근할 수 있는 공간과 가능한 미시적 배치가 늘어납니다. 같은 수의 점을 설명용으로 배치했으며 실제 분자 궤적이나 실험 데이터가 아닙니다.",
    "sourceUrl": "https://openstax.org/books/university-physics-volume-2/pages/4-6-entropy",
    "sourceLabel": "OpenStax University Physics 2, 엔트로피",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "quantum",
    "afterSection": "scene-3",
    "title": "두 경로와 누적된 점",
    "src": "/images/essays/quantum/concept.svg",
    "alt": "두 슬릿을 지나는 경로와 검출 점이 쌓이는 화면을 구분한 양자 실험 개념도",
    "caption": "두 슬릿 사고 실험의 경로와 검출 화면을 간략히 그렸습니다. 곡선은 두 경로의 개념적 표시이며 관측한 입자의 궤적이 아닙니다. 누적 분포를 이해하기 위한 개념도이며 히타치 전자 바이프리즘 장치를 두 슬릿으로 재현한 그림이 아닙니다.",
    "sourceUrl": "https://www.feynmanlectures.caltech.edu/III_01.html",
    "sourceLabel": "파인먼 물리학 강의 3권 1장, 양자적 행동",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "plate-tectonics",
    "afterSection": "scene-3",
    "title": "해령 양쪽에 남은 자기 기록",
    "src": "/images/essays/plate-tectonics/concept.svg",
    "alt": "해령 양쪽의 대칭적인 자기 띠와 벌어지는 방향을 표시한 개념도",
    "caption": "해령에서 멀어지는 암석에 남는 두 자화 방향을 대칭 띠로 단순화했습니다. 실제 해저 지도나 자기 연대 측정값이 아니며 띠의 폭도 데이터가 아닙니다.",
    "sourceUrl": "https://www.nps.gov/subjects/geology/plate-tectonics-the-unifying-theory-of-geology.htm",
    "sourceLabel": "미국 국립공원관리청, 지질학의 통합 이론",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "dna-code",
    "afterSection": "scene-3",
    "title": "염기쌍과 코돈은 다른 규칙",
    "src": "/images/essays/dna-code/concept.svg",
    "alt": "DNA의 A와 T, G와 C 염기쌍을 RNA의 세 염기 단위 읽기와 구분한 그림",
    "caption": "DNA의 상보적 염기쌍과 RNA 서열을 세 염기씩 읽는 유전암호를 나눠 표시했습니다. 그림은 설명용이며 특정 유전자나 단백질의 실제 서열을 나타내지 않습니다.",
    "sourceUrl": "https://www.genome.gov/about-genomics/fact-sheets/Deoxyribonucleic-Acid-Fact-Sheet",
    "sourceLabel": "NHGRI, DNA 안내",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "printing",
    "afterSection": "scene-3",
    "title": "같은 판에서 여러 부가 나온다",
    "src": "/images/essays/printing/concept.svg",
    "alt": "한 인쇄판의 같은 글자 배열이 세 장의 종이에 반복되는 개념도",
    "caption": "같은 판은 여러 부를 만들고 그 판에 남은 오류도 함께 반복할 수 있습니다. 그림의 글자와 문서는 설명용이며 특정 판본의 도판이나 문장을 복제하지 않았습니다.",
    "sourceUrl": "https://idp.bl.uk/collection/51FDAEAFB4A24E2E9981692A98130BC8/",
    "sourceLabel": "British Library · IDP 금강경 Or.8210/P.2",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "steam-work",
    "afterSection": "scene-2",
    "title": "뜨거운 실린더와 분리 응축기",
    "src": "/images/essays/steam-work/concept.svg",
    "alt": "실린더와 별도의 응축기를 연결하고 뜨거운 부분과 차가운 부분을 구분한 그림",
    "caption": "실린더와 응축을 위한 공간을 나누는 발상을 보여 줍니다. 와트 기관의 실제 설계도나 성능 수치가 아니라 원고가 설명하는 온도 역할의 구분입니다.",
    "sourceUrl": "https://blog.sciencemuseum.org.uk/james-watt-and-the-separate-condenser/",
    "sourceLabel": "Science Museum · James Watt and the separate condenser",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "electromagnetism",
    "afterSection": "scene-1",
    "title": "변화할 때 나타나는 유도 전류",
    "src": "/images/essays/electromagnetism/concept.svg",
    "alt": "철 고리의 두 코일과 연결·끊김에 대응하는 잠시의 전류를 구분한 개념도",
    "caption": "한 코일의 회로를 연결하거나 끊을 때 다른 코일에 잠시 전류가 나타난다는 실험의 핵심을 그렸습니다. 변화와 반응의 표시는 실측 파형이 아니라 개념도입니다.",
    "sourceUrl": "https://www.rigb.org/explore-science/explore/collection/michael-faradays-ring-coil-apparatus",
    "sourceLabel": "Royal Institution · Michael Faraday's ring-coil apparatus",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "shannon",
    "afterSection": "scene-1",
    "title": "네 메시지에 붙인 두 비트",
    "src": "/images/essays/shannon/concept.svg",
    "alt": "네 메시지를 00, 01, 10, 11의 두 비트 부호로 구별한 예시",
    "caption": "네 가지 메시지에 서로 다른 두 비트 꼬리표를 붙인 예시입니다. 실제 메시지의 뜻이나 확률을 반영한 것이 아니며 모든 메시지의 평균 정보량이 늘 두 비트라는 뜻도 아닙니다.",
    "sourceUrl": "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf",
    "sourceLabel": "Shannon · A Mathematical Theory of Communication (1948)",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "feedback",
    "afterSection": "scene-2",
    "title": "측정값이 돌아오는 고리",
    "src": "/images/essays/feedback/concept.svg",
    "alt": "목표에서 실행과 결과를 거쳐 측정값이 되돌아오는 되먹임 고리",
    "caption": "목표, 실행, 결과, 측정의 경로와 측정값이 돌아오는 지연을 표시한 단순 예시입니다. 되먹임이 있다는 사실만으로 안정성이나 목표의 적절함이 보장되지는 않습니다.",
    "sourceUrl": "https://webhomes.maths.ed.ac.uk/~v1ranick/papers/maxwell1",
    "sourceLabel": "Maxwell · On Governors (1868), University of Edinburgh 제공",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "programmable-weaving",
    "afterSection": "scene-2",
    "title": "카드의 구멍에서 날실의 선택으로",
    "src": "/images/essays/programmable-weaving/concept.svg",
    "alt": "구멍 난 카드의 선택 패턴이 올라가는 날실로 이어지는 직조 개념도",
    "caption": "도안을 옮긴 카드와 그에 대응하는 날실 선택을 간략히 연결했습니다. 실제 자카르 장치의 기계 설계나 직물 무늬를 복제한 그림은 아닙니다.",
    "sourceUrl": "https://www.scienceandindustrymuseum.org.uk/objects-and-stories/jacquard-loom",
    "sourceLabel": "Science and Industry Museum · The story of the Jacquard loom",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "turing-computation",
    "afterSection": "scene-2",
    "title": "읽고 쓰고 이동하는 한 단계",
    "src": "/images/essays/turing-computation/concept.svg",
    "alt": "테이프의 현재 칸, 읽기·쓰기 헤드와 상태 규칙의 관계를 보여 주는 계산 모형",
    "caption": "테이프의 기호를 읽고 상태 규칙에 따라 쓰거나 이동하는 단계를 정리했습니다. 이 그림이 모든 프로그램의 종료 여부를 판정하는 절차를 뜻하지는 않습니다.",
    "sourceUrl": "https://www.cs.virginia.edu/~robins/Turing_Paper_1936.pdf",
    "sourceLabel": "Turing · On Computable Numbers, University of Virginia 제공 사본",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "germ-theory",
    "afterSection": "scene-3",
    "title": "공기와 먼지의 경로를 나누기",
    "src": "/images/essays/germ-theory/concept.svg",
    "alt": "백조목의 굽은 부분에 입자가 남고 공기는 배양액 쪽으로 이어지는 경로의 개념도",
    "caption": "백조목 플라스크 실험이 구분한 공기 접촉과 입자 유입을 표시했습니다. 실제 실험 도판이나 미생물 사진을 복제하지 않았으며 오늘의 의료 지침을 제시하는 그림도 아닙니다.",
    "sourceUrl": "https://openstax.org/books/microbiology/pages/3-2-foundations-of-modern-cell-theory",
    "sourceLabel": "OpenStax, Foundations of Modern Cell Theory",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "reproducibility",
    "afterSection": "scene-1",
    "title": "다시 확인하는 세 가지 질문",
    "src": "/images/essays/reproducibility/concept.svg",
    "alt": "같은 자료와 계산의 재현, 새 자료의 반복, 다른 조건의 일반화를 비교한 그림",
    "caption": "원고가 사용하는 National Academies의 구분에 따라 같은 입력과 계산, 새 자료를 통한 반복, 다른 조건으로의 일반화를 나눴습니다. 분야에 따라 용어 사용은 달라질 수 있습니다.",
    "sourceUrl": "https://www.nationalacademies.org/read/25303/chapter/3",
    "sourceLabel": "National Academies, Reproducibility and Replicability in Science, 2019, Summary",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "atomic-age",
    "afterSection": "scene-1",
    "title": "발견에서 사용까지 남는 결정",
    "src": "/images/essays/atomic-age/concept.svg",
    "alt": "관찰과 해석에서 연구 조직과 정책 결정으로 이어지는 서로 다른 단계의 도식",
    "caption": "연구의 관찰과 해석, 조직의 구성, 정책 결정을 구분한 편집 개념도입니다. 핵무기 설계나 재료 생산 과정을 나타내지 않으며 발견이 사용을 자동으로 정한 것도 아닙니다.",
    "sourceUrl": "https://www.nature.com/articles/143239a0",
    "sourceLabel": "Meitner와 Frisch, Disintegration of Uranium by Neutrons, Nature, 1939",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "archives-silence",
    "afterSection": "scene-4",
    "title": "기록의 빈칸에 남는 질문",
    "src": "/images/essays/archives-silence/concept.svg",
    "alt": "기록된 항목과 빈칸 옆에 작성 목적·작성자·보존 조건의 질문을 놓은 도식",
    "caption": "작성 목적, 기록하는 사람, 보존된 항목을 확인한 뒤 빈칸을 해석해야 합니다. 설명용으로 만든 문서 도식이며 실제 인물이나 사료의 내용을 재현하지 않았습니다.",
    "sourceUrl": "https://www.archives.gov/education/lessons/worksheets",
    "sourceLabel": "미국 국립문서기록관리청, Document Analysis",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "earthrise",
    "afterSection": "scene-2",
    "title": "달 궤도에서 바뀌는 관측 시점",
    "src": "/images/essays/earthrise/concept.svg",
    "alt": "달 주변의 우주선 위치와 바깥의 지구를 연결해 시점 변화를 보여 주는 개념도",
    "caption": "달을 도는 우주선의 시점이 달라지면 지구와 달의 지평선이 이루는 구도도 달라집니다. 실제 Earthrise 사진이나 임무 궤적이 아니라 관측 위치를 설명하는 개념도입니다.",
    "sourceUrl": "https://www.nasa.gov/history/50-years-ago-apollo-8-in-lunar-orbit/",
    "sourceLabel": "NASA, Apollo 8 in Lunar Orbit",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "climate-ice",
    "afterSection": "scene-2",
    "title": "얼음의 연대와 갇힌 공기의 연대",
    "src": "/images/essays/climate-ice/concept.svg",
    "alt": "눈이 쌓이고 공기가 갇히는 서로 다른 단계를 표시한 빙핵 개념도",
    "caption": "눈이 얼음이 되는 과정과 공기가 갇히는 과정을 나눠 보여 줍니다. 같은 깊이의 얼음과 기체에 적용할 연대 정보를 구분하는 개념도이며 실제 빙핵 데이터가 아닙니다.",
    "sourceUrl": "https://www.ncei.noaa.gov/products/paleoclimatology/ice-core",
    "sourceLabel": "NOAA NCEI, Ice Core",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  },
  {
    "slug": "model-limits",
    "afterSection": "scene-1",
    "title": "한 예측에서 갈리는 두 결정",
    "src": "/images/essays/model-limits/concept.svg",
    "alt": "대기시간 20분이라는 가상 예측을 방문자 안내와 인력 배치의 두 결정으로 나눈 그림",
    "caption": "원고의 가상 대기시간 20분 사례를 정리했습니다. 방문자 안내와 인력 배치에는 같은 예측 외에도 서로 다른 판단 조건이 필요하며 실제 운영 데이터를 그린 것은 아닙니다.",
    "sourceUrl": "https://physics.nist.gov/cuu/Uncertainty/basic.html",
    "sourceLabel": "NIST, Basic Definitions of Uncertainty",
    "width": 640,
    "height": 460,
    "credit": "Biz2Lab 편집 개념도 · 원자료의 이미지나 실측 데이터 복제 아님"
  }
];

export function getEssayMedia(slug: string) { return essayMedia.find(figure => figure.slug === slug); }
