export type EssayPhoto = {
  slug: string; section: string; title: string; alt: string; caption: string;
  credit: string; creator?: string | null; creatorType?: "Person" | "Organization";
  sourceUrl: string; sourceLabel: string; license: string; licenseUrl: string;
  widths: readonly number[]; width: number; height: number; keepDiagram: boolean; kind?: string; assetVersion: string;
};

// Individually checked source photos and historical records; manuscripts remain unchanged.
export const essayPhotos: readonly EssayPhoto[] = [
  {
    "slug": "earthrise",
    "section": "scene-1",
    "title": "아폴로 8호가 촬영한 Earthrise",
    "alt": "달의 회색 지평선 위로 푸른 지구가 떠오르는 아폴로 8호의 1968년 실제 사진",
    "caption": "1968년 12월 24일, 아폴로 8호의 빌 앤더스가 달 궤도에서 촬영한 지구입니다. NASA가 공개한 원본 사진을 사용했습니다.",
    "credit": "NASA / Bill Anders · 1968년 12월 24일",
    "creator": "Bill Anders",
    "sourceUrl": "https://www.nasa.gov/image-article/apollo-8-earthrise/",
    "sourceLabel": "NASA: Apollo 8 Earthrise",
    "license": "Public domain — NASA 개별 이미지",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:NASA-Apollo8-Dec24-Earthrise.jpg",
    "widths": [
      480,
      768,
      1041
    ],
    "width": 1041,
    "height": 1000,
    "keepDiagram": false,
    "assetVersion": "2caee02c7bcb"
  },
  {
    "slug": "longitude",
    "section": "scene-1",
    "title": "존 해리슨의 H4 내부 장치",
    "alt": "그리니치 왕립 천문대에 전시된 해리슨 H4의 톱니바퀴와 내부 장치를 촬영한 사진",
    "caption": "경도 문제를 해결하려던 해리슨의 H4 내부입니다. 2015년 그리니치 왕립 천문대에서 촬영한 유물 사진이며, 항해 중의 모습을 재현한 이미지는 아닙니다.",
    "credit": "Photograph by Mike Peel (www.mikepeel.net) · 2015년 4월 15일",
    "creator": "Mike Peel",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Harrison_H4_clockwork_1.jpg",
    "sourceLabel": "Wikimedia Commons: Harrison H4 clockwork 1",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 853,
    "keepDiagram": true,
    "assetVersion": "fdc795963046"
  },
  {
    "slug": "frankenstein-ai",
    "section": "scene-1",
    "title": "1831년판 프랑켄슈타인의 권두 삽화",
    "alt": "빅터 프랑켄슈타인과 그가 만든 존재를 그린 1831년판 권두 삽화의 원자료 복제 이미지",
    "caption": "테오도르 폰 홀스트의 1831년판 권두 삽화입니다. 소설이 당대에 어떻게 시각화됐는지 보여 주는 역사 원자료이며, 실제 실험이나 인물을 촬영한 사진은 아닙니다.",
    "credit": "Theodor von Holst (1810–1844) · 1831년판 권두 삽화 · Wikimedia Commons 원자료",
    "creator": "Theodor von Holst",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Frontispiece_to_Frankenstein_1831.jpg",
    "sourceLabel": "Wikimedia Commons: Frontispiece to Frankenstein 1831",
    "license": "Public domain — 역사 작품의 충실한 복제",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 1653,
    "keepDiagram": false,
    "assetVersion": "025804057d8d"
  },
  {
    "slug": "eratosthenes",
    "section": "scene-1",
    "title": "그림자를 읽는 해시계",
    "alt": "베이징 고관상대의 해시계와 그림자를 만드는 막대",
    "caption": "베이징 고관상대의 해시계입니다. 막대와 그림자를 관측하는 실제 기구의 예이며, 에라토스테네스가 사용한 원래 도구의 사진은 아닙니다.",
    "kind": "artifact-photo",
    "credit": "EditQ",
    "creator": "EditQ",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gnomon_Sundial,_Beijing_Ancient_Observatory.jpg",
    "sourceLabel": "Wikimedia Commons: Gnomon Sundial, Beijing Ancient Observatory.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 960,
    "keepDiagram": true,
    "assetVersion": "11b16b1828d8"
  },
  {
    "slug": "calendar",
    "section": "scene-1",
    "title": "1582년 달력 개혁을 기념한 역사 작품",
    "alt": "그레고리력 개혁을 기념해 제작된 1582년 역사 회화의 복제 이미지",
    "caption": "Scipio Turaminus 이름으로 전하는 1582년 달력 개혁 기념 작품입니다. 달력 개혁이 사람들의 공적 시간 체계와 연결됐던 맥락을 보여 주는 역사 원자료입니다.",
    "kind": "historical-source",
    "credit": "Scipio Turaminus",
    "creator": "Scipio Turaminus",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scipio-Turaminus_Gregorian_calendar_1582.jpg",
    "sourceLabel": "Wikimedia Commons: Scipio-Turaminus Gregorian calendar 1582.jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Scipio-Turaminus_Gregorian_calendar_1582.jpg",
    "widths": [
      480,
      590
    ],
    "width": 590,
    "height": 418,
    "keepDiagram": true,
    "assetVersion": "b0c4cdbc32a4"
  },
  {
    "slug": "maps",
    "section": "scene-1",
    "title": "메르카토르의 1569년 세계지도",
    "alt": "18개 시트를 이어 붙인 메르카토르의 1569년 세계지도 원자료",
    "caption": "1569년 세계지도의 바젤 소장 사본을 복제한 이미지입니다. 항해를 위한 지도에서 위도에 따라 형태와 크기가 어떻게 달라지는지 실제 역사 지도와 함께 볼 수 있습니다.",
    "kind": "historical-source",
    "credit": "Gerardus Mercator · 바젤 사본 복제: Wilhelm Krücken · 공개된 중간 해상도 파일",
    "creator": "Gerardus Mercator",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mercator_1569_world_map_composite.jpg",
    "sourceLabel": "Wikimedia Commons: Mercator 1569 world map composite.jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Mercator_1569_world_map_composite.jpg",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 813,
    "keepDiagram": true,
    "assetVersion": "6cda27d89f2a"
  },
  {
    "slug": "relativity",
    "section": "scene-1",
    "title": "세슘 원자시계의 실제 장치",
    "alt": "HP 5061A 세슘 빔 주파수 표준 장치의 전면",
    "caption": "HP 5061A 세슘 원자시계 장치입니다. 이동하는 시계의 시간을 비교하려면 실제 시계와 동기화·측정 조건부터 확인해야 한다는 본문의 질문과 연결됩니다.",
    "kind": "artifact-photo",
    "credit": "Binarysequence",
    "creator": "Binarysequence",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HP_5061A_Cesium_Beam_Frequency_Standard.JPG",
    "sourceLabel": "Wikimedia Commons: HP 5061A Cesium Beam Frequency Standard.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 720,
    "keepDiagram": true,
    "assetVersion": "8dd57750596e"
  },
  {
    "slug": "telescope",
    "section": "scene-1",
    "title": "갈릴레오 박물관의 17세기 망원경",
    "alt": "갈릴레오 박물관에 전시된 길이가 다른 17세기 망원경들",
    "caption": "메디치 컬렉션에 속한 17세기 망원경들의 전시 사진입니다. 갈릴레이가 관측한 당일의 장면이 아니라 당시 관측 기구의 물리적인 모습을 보여 줍니다.",
    "kind": "artifact-photo",
    "credit": "C messier",
    "creator": "C messier",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:17th_century_telescopes_in_Galileo_Museum_0640.jpg",
    "sourceLabel": "Wikimedia Commons: 17th century telescopes in Galileo Museum 0640.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 960,
    "keepDiagram": false,
    "assetVersion": "9c3800fac6d0"
  },
  {
    "slug": "microscope",
    "section": "scene-1",
    "title": "훅이 기록한 코르크의 조직",
    "alt": "로버트 훅의 Micrographia 도판 XI에 그려진 코르크의 세포와 기공",
    "caption": "1665년 『Micrographia』의 도판 XI입니다. 현미경으로 본 코르크를 훅이 어떻게 기록했는지 보여 주는 역사 도판으로, 현대 현미경의 촬영 사진과 구분됩니다.",
    "kind": "historical-source",
    "credit": "Robert Hooke (1635–1703) · National Library of Wales 공개 원자료",
    "creator": "Robert Hooke (1635-1703)",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Micrographia_Schem_11.jpg",
    "sourceLabel": "Wikimedia Commons: Micrographia Schem 11.jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Micrographia_Schem_11.jpg",
    "widths": [
      480,
      768,
      1213
    ],
    "width": 1213,
    "height": 1769,
    "keepDiagram": false,
    "assetVersion": "0863c0e7f8ce"
  },
  {
    "slug": "evolution",
    "section": "scene-1",
    "title": "다윈의 1837년 노트",
    "alt": "I think라는 글과 가지 모양 스케치가 있는 다윈의 노트 페이지",
    "caption": "다윈의 종 변형 노트 B, 36쪽에 남은 1837년 스케치입니다. 생명의 관계를 사다리보다 가지로 생각하려던 실제 기록을 보여 줍니다.",
    "kind": "historical-source",
    "credit": "Charles Darwin · Notebook B, p. 36 · Darwin Online / Wikimedia Commons",
    "creator": "Charles Darwin",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Darwin_Tree_1837.png",
    "sourceLabel": "Wikimedia Commons: Darwin Tree 1837.png",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Darwin_Tree_1837.png",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 2086,
    "keepDiagram": true,
    "assetVersion": "4bc858d91142"
  },
  {
    "slug": "mendel",
    "section": "scene-1",
    "title": "실제로 자라는 완두 꼬투리",
    "alt": "꽃잎 흔적과 어린 녹색 꼬투리가 있는 완두 Pisum sativum",
    "caption": "완두의 어린 꼬투리를 촬영한 식물 사진입니다. 멘델의 실험 개체나 특정 교배 결과라는 뜻은 아니며, 여러 형질을 구분해 관찰한 식물의 모습을 보여 줍니다.",
    "kind": "plant-photo",
    "credit": "Chmee2",
    "creator": "Chmee2",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Young_pod_of_Pisum_sativum_(1).JPG",
    "sourceLabel": "Wikimedia Commons: Young pod of Pisum sativum (1).JPG",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 853,
    "keepDiagram": true,
    "assetVersion": "b4ecfae3b7b1"
  },
  {
    "slug": "periodic-table",
    "section": "scene-1",
    "title": "멘델레예프의 1869년 표",
    "alt": "원소 기호와 수치, 물음표가 배열된 멘델레예프의 1869년 주기율표",
    "caption": "1869년 처음 발표한 표의 역사 원자료입니다. 오늘날의 원자번호 순 표와 구분해, 당시의 배열과 남겨 둔 빈자리를 살펴볼 수 있습니다.",
    "kind": "historical-source",
    "credit": "Dmitri Mendeleev",
    "creator": "Dmitri Mendeleev",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mendeleev%27s_periodic_table_(1869_year).jpg",
    "sourceLabel": "Wikimedia Commons: Mendeleev's periodic table (1869 year).jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Mendeleev%27s_periodic_table_(1869_year).jpg",
    "widths": [
      480,
      619
    ],
    "width": 619,
    "height": 784,
    "keepDiagram": true,
    "assetVersion": "59c3b63036b0"
  },
  {
    "slug": "entropy",
    "section": "scene-1",
    "title": "깨진 유리잔의 실제 모습",
    "alt": "바닥에 깨진 조각이 놓여 있는 유리잔",
    "caption": "깨진 유리잔을 촬영한 사진입니다. 본문의 되돌리기 어려운 변화라는 질문을 여는 예이며, 이 사진만으로 엔트로피 값을 측정한 것은 아닙니다.",
    "kind": "object-photo",
    "credit": "Santeri Viinamäki",
    "creator": "Santeri Viinamäki",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Broken_drinking_glass.JPG",
    "sourceLabel": "Wikimedia Commons: Broken drinking glass.JPG",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 1707,
    "keepDiagram": true,
    "assetVersion": "d0302d407476"
  },
  {
    "slug": "quantum",
    "section": "scene-1",
    "title": "한 개씩 쌓인 전자의 검출 기록",
    "alt": "전자의 검출점이 누적되면서 간섭무늬가 나타나는 다섯 단계의 실제 실험 기록",
    "caption": "도노무라 연구진의 단일 전자 간섭 기록입니다. 이 실험은 전자 바이프리즘을 사용했으며 물리적인 두 슬릿 장치와 구분됩니다. 위에서 아래로 검출점이 누적되는 과정을 보여 줍니다.",
    "kind": "experiment-record",
    "credit": "실험: Akira Tonomura 연구진 · Commons 파일: Belsazar · 도노무라의 허락으로 제공",
    "creator": "user:Belsazar",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Double-slit_experiment_results_Tonomura_2.jpg",
    "sourceLabel": "Wikimedia Commons: Double-slit experiment results Tonomura 2.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 2784,
    "keepDiagram": true,
    "assetVersion": "b39547b37dcb"
  },
  {
    "slug": "plate-tectonics",
    "section": "scene-1",
    "title": "아이슬란드에서 드러난 갈라진 지형",
    "alt": "아이슬란드 싱벨리르 국립공원의 알만나갸 균열 지형",
    "caption": "싱벨리르 국립공원의 알만나갸 지형 사진입니다. 북아메리카판과 유라시아판의 경계 지역을 보여 주며, 사진 한 장만으로 판의 이동 속도를 측정한 것은 아닙니다.",
    "kind": "place-photo",
    "credit": "Olga Ernst",
    "creator": "Olga Ernst",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Almannagj%C3%A1_rift_at_%C3%9Eingvellir_National_Park.jpg",
    "sourceLabel": "Wikimedia Commons: Almannagjá rift at Þingvellir National Park.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "widths": [
      480,
      768,
      1280
    ],
    "width": 1280,
    "height": 854,
    "keepDiagram": true,
    "assetVersion": "17c174ba47b0"
  },
  {
    "slug": "dna-code",
    "section": "scene-1",
    "title": "DNA 이중나선의 물리적 모형",
    "alt": "런던 과학박물관에 전시된 DNA 이중나선 모형",
    "caption": "런던 과학박물관에 전시된 크릭·왓슨 DNA 모형의 사진입니다. 분자의 구조를 설명하는 물리적 모형으로, 실제 DNA 분자를 직접 촬영한 영상과 구분됩니다.",
    "kind": "model-photo",
    "credit": "사진: Alkivar · DNA 모형, 런던 과학박물관 · 촬영자가 Public domain으로 공개",
    "creator": "User:Alkivar",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DNA_Model_Crick-Watson.jpg",
    "sourceLabel": "Wikimedia Commons: DNA Model Crick-Watson.jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:DNA_Model_Crick-Watson.jpg",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 1280,
    "keepDiagram": true,
    "assetVersion": "f61930d6ed4a"
  },
  {
    "slug": "printing",
    "section": "scene-1",
    "title": "1377년 직지의 실제 지면",
    "alt": "금속활자로 인쇄된 1377년 직지의 두 페이지",
    "caption": "프랑스 국립도서관이 보존·디지털화한 『직지』의 4v–5r쪽입니다. 복제 속도와 판본의 차이를 이야기하기 전에 실제 인쇄 지면을 볼 수 있습니다.",
    "kind": "historical-source",
    "credit": "『직지』, 1377 · Bibliothèque nationale de France, Gallica · Wikimedia Commons 원자료",
    "creator": null,
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jikji_pages.jpg",
    "sourceLabel": "Wikimedia Commons: Jikji pages.jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Jikji_pages.jpg",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 755,
    "keepDiagram": false,
    "assetVersion": "2caf9b33b508"
  },
  {
    "slug": "steam-work",
    "section": "scene-1",
    "title": "보존된 볼턴·와트 증기기관",
    "alt": "시드니 파워하우스 박물관에 전시된 볼턴·와트 증기기관",
    "caption": "1785년에 제작된 볼턴·와트 증기기관을 2014년 박물관에서 촬영한 사진입니다. 당시 공장의 작업 장면을 재현한 이미지 대신 보존된 기계를 보여 줍니다.",
    "kind": "artifact-photo",
    "credit": "David Maciulaitis from Auckland, New Zealand",
    "creator": "David Maciulaitis from Auckland, New Zealand",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Boulton_%26_Watt_steam_engine,_Sydney_Powerhouse_Museum,_2014_(15240699214).jpg",
    "sourceLabel": "Wikimedia Commons: Boulton & Watt steam engine, Sydney Powerhouse Museum, 2014 (15240699214).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 643,
    "keepDiagram": false,
    "assetVersion": "c7f6584edbaf"
  },
  {
    "slug": "electromagnetism",
    "section": "scene-1",
    "title": "패러데이의 고리 장치",
    "alt": "철 고리에 양쪽으로 전선이 감겨 있는 패러데이의 유도 실험 장치",
    "caption": "패러데이의 고리 장치를 1922년 기술 간행물에 실은 역사 사진입니다. 전류의 변화를 다른 회로에서 관찰한 장치의 실제 구조를 보여 줍니다.",
    "kind": "historical-photo",
    "credit": "촬영자 미상 · IEE Proceedings, 1922, Plate XIV · 패러데이 고리 장치의 역사 사진",
    "creator": null,
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Faraday_ring_transformer.jpg",
    "sourceLabel": "Wikimedia Commons: Faraday ring transformer.jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Faraday_ring_transformer.jpg",
    "widths": [
      480,
      500
    ],
    "width": 500,
    "height": 485,
    "keepDiagram": true,
    "assetVersion": "1dc95831c28a"
  },
  {
    "slug": "shannon",
    "section": "scene-1",
    "title": "종이테이프를 읽는 전송 장치",
    "alt": "천공 종이테이프를 읽는 Creed 6S/2 장치",
    "caption": "블레츨리 파크 국립컴퓨팅박물관의 Creed 6S/2 종이테이프 판독기입니다. 기호를 부호로 다루는 실제 통신 기구의 예이며, 섀넌이 직접 사용한 장치라고 주장하지 않습니다.",
    "kind": "artifact-photo",
    "credit": "TedColes",
    "creator": "TedColes",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Creed_model_6S-2_paper_tape_reader.jpg",
    "sourceLabel": "Wikimedia Commons: Creed model 6S-2 paper tape reader.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 720,
    "keepDiagram": true,
    "assetVersion": "d79365963a27"
  },
  {
    "slug": "feedback",
    "section": "scene-1",
    "title": "증기기관의 원심 조속기",
    "alt": "볼턴·와트 증기기관에 달린 두 개의 추와 축으로 구성된 원심 조속기",
    "caption": "런던 과학박물관의 볼턴·와트 증기기관에 있는 와트식 원심 조속기입니다. 회전 변화가 밸브 제어로 되돌아가는 물리적 기구를 보여 줍니다.",
    "kind": "artifact-photo",
    "credit": "Dr. Mirko Junge",
    "creator": "Dr. Mirko Junge",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Boulton_and_Watt_centrifugal_governor-MJ.jpg",
    "sourceLabel": "Wikimedia Commons: Boulton and Watt centrifugal governor-MJ.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 1280,
    "keepDiagram": true,
    "assetVersion": "bc819534c327"
  },
  {
    "slug": "programmable-weaving",
    "section": "scene-1",
    "title": "천공카드와 자카르 직기",
    "alt": "스코틀랜드 국립박물관의 자카르 직기와 연결된 천공카드",
    "caption": "스코틀랜드 국립박물관에 전시된 자카르 직기입니다. 종이카드의 구멍을 기계의 동작과 연결한 실제 기구를 볼 수 있습니다.",
    "kind": "artifact-photo",
    "credit": "Stephencdickson",
    "creator": "Stephencdickson",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Jacquard_loom_showing_information_punchcards,_National_Museum_of_Scotland.jpg",
    "sourceLabel": "Wikimedia Commons: A Jacquard loom showing information punchcards, National Museum of Scotland.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 639,
    "keepDiagram": true,
    "assetVersion": "9dea80c1e9e9"
  },
  {
    "slug": "turing-computation",
    "section": "scene-1",
    "title": "블레츨리 파크의 봄브 복원품",
    "alt": "블레츨리 파크 박물관의 영국 봄브 복원품에 배열된 회전 장치들",
    "caption": "영국 봄브를 복원한 전시 기계입니다. 계산과 암호 해독의 역사적 기구를 보여 주며, 추상적인 튜링 기계의 실물이나 모든 문제를 푸는 장치를 뜻하지 않습니다.",
    "kind": "replica-photo",
    "credit": "Photograph by Tom Yates · Bombe Rebuild Project 복원 작업 · Wikimedia Commons 파일은 기존 크롭본",
    "creator": "Tom Yates",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bombe-rebuild.jpg",
    "sourceLabel": "Wikimedia Commons: Bombe-rebuild.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 702,
    "keepDiagram": true,
    "assetVersion": "fd3a0457a7cb"
  },
  {
    "slug": "germ-theory",
    "section": "scene-1",
    "title": "1860–1864년 프랑스의 보존 플라스크",
    "alt": "긴 목과 손글씨 라벨이 있는 19세기 유리 플라스크",
    "caption": "Wellcome Collection이 보존한 프랑스산 1860–1864년 플라스크입니다. 사진에서 긴 직선 목과 유리 용기의 형태를 볼 수 있습니다. 소장 기록만으로 파스퇴르가 이 유물을 직접 사용했다고 확인할 수는 없다는 기관의 설명을 따릅니다.",
    "kind": "artifact-photo",
    "credit": "Wellcome Collection / Wellcome Images · L0057230",
    "creator": null,
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Glass_flask_used_by_Louis_Pasteur,_France,_1860-1864_Wellcome_L0057230.jpg",
    "sourceLabel": "Wikimedia Commons: Glass flask used by Louis Pasteur, France, 1860-1864 Wellcome L0057230.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 1443,
    "keepDiagram": false,
    "assetVersion": "2b4f2350d7c0"
  },
  {
    "slug": "reproducibility",
    "section": "scene-1",
    "title": "기록해야 할 실제 실험 조건",
    "alt": "피펫과 시험관 등 실험 장비가 놓인 작업대",
    "caption": "실험 장비가 놓인 실제 작업대 사진입니다. 장비와 절차도 반복 실험에서 기록할 조건의 예이며, 본문에 인용된 심리학 연구 100건의 실험실을 촬영한 사진은 아닙니다.",
    "kind": "lab-photo",
    "credit": "Photograph by Luca Volpi (Goldmund100)",
    "creator": "Luca Volpi",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Laboratory_desk.jpg",
    "sourceLabel": "Wikimedia Commons: Laboratory desk.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 599,
    "keepDiagram": true,
    "assetVersion": "15ee4932d5f6"
  },
  {
    "slug": "atomic-age",
    "section": "scene-1",
    "title": "시카고 파일 1호의 조립 기록",
    "alt": "시카고 파일 1호를 조립하던 중 쌓인 흑연 블록층의 역사 사진",
    "caption": "시카고 파일 1호 조립 중 흑연 블록층을 촬영한 기록입니다. 원자핵에 관한 지식이 실제 시설과 조직의 선택으로 이어진 모습을 보여 줍니다.",
    "kind": "historical-photo",
    "credit": "U.S. Department of Energy / ENERGY.GOV · HD.5A.026",
    "creator": "ENERGY.GOV",
    "creatorType": "Organization",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HD.5A.026_(10692858884).jpg",
    "sourceLabel": "Wikimedia Commons: HD.5A.026 (10692858884).jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:HD.5A.026_(10692858884).jpg",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 1217,
    "keepDiagram": false,
    "assetVersion": "bb342c5f227a"
  },
  {
    "slug": "archives-silence",
    "section": "scene-1",
    "title": "1865년 해방민 혼인 등록부",
    "alt": "해방민의 혼인을 기록한 1865년 등록부의 손글씨 지면",
    "caption": "미국 국립문서기록관리청이 보존한 1865년 해방민 혼인 등록부의 한 지면입니다. 남은 기록의 작성 목적과 기록되지 않은 삶을 함께 묻는 본문과 연결됩니다.",
    "kind": "historical-source",
    "credit": "U.S. National Archives and Records Administration · NARA 594898, page 3 · 작성자 미상",
    "creator": null,
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Register_of_Marriages_Among_Freedmen_During_1865_-_NARA_-_594898_(page_3).jpg",
    "sourceLabel": "Wikimedia Commons: Register of Marriages Among Freedmen During 1865 - NARA - 594898 (page 3).jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Register_of_Marriages_Among_Freedmen_During_1865_-_NARA_-_594898_(page_3).jpg",
    "widths": [
      480,
      500
    ],
    "width": 500,
    "height": 397,
    "keepDiagram": false,
    "assetVersion": "6dddd4865b27"
  },
  {
    "slug": "climate-ice",
    "section": "scene-1",
    "title": "빙하 코어 속에 남은 층",
    "alt": "GISP2의 깊이 1855미터에서 얻은 빙하 코어 단면의 밝고 어두운 층",
    "caption": "GISP2 빙하 코어의 깊이 1855m 지점에서 얻은 19cm 구간입니다. 빛을 비춰 드러낸 층 구조를 보여 주며, 기포 속 기체의 조성을 사진만으로 읽는 것은 아닙니다.",
    "kind": "sample-photo",
    "credit": "NOAA 공개 자료 · GISP2 ice core, 1855m · Wikimedia Commons 보존본",
    "creator": null,
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:GISP2_1855m_ice_core_layers.png",
    "sourceLabel": "Wikimedia Commons: GISP2 1855m ice core layers.png",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:GISP2_1855m_ice_core_layers.png",
    "widths": [
      480,
      500
    ],
    "width": 500,
    "height": 226,
    "keepDiagram": true,
    "assetVersion": "c06c370b2a7a"
  },
  {
    "slug": "model-limits",
    "section": "scene-1",
    "title": "예측과 결정이 만나는 실제 장소",
    "alt": "독일 오커스하우젠의 비어 있는 버스 정류장",
    "caption": "독일 오커스하우젠의 실제 버스 정류장 사진입니다. 본문의 대기시간과 배치 결정 사례를 떠올리는 장소의 예이며, 이 정류장의 실제 예측 성능이나 대기시간을 측정한 자료는 아닙니다.",
    "kind": "place-photo",
    "credit": "LudwigSebastianMicheler",
    "creator": "LudwigSebastianMicheler",
    "creatorType": "Person",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Empty_bus_stop_in_Ockershausen_-_Happy_day%3F_2016-10-17.jpg",
    "sourceLabel": "Wikimedia Commons: Empty bus stop in Ockershausen - Happy day? 2016-10-17.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 1280,
    "keepDiagram": true,
    "assetVersion": "0a50124de9e2"
  }
];

export function getEssayPhoto(slug: string) { return essayPhotos.find(photo => photo.slug === slug); }
export function essayPhotoSrc(photo: EssayPhoto, width: number, format: "avif" | "webp" | "jpg") {
  return `/images/essays/${photo.slug}/source-photo/${photo.assetVersion}/${width}.${format}`;
}
