// Navigation copy joins the subject just read to the next essay; manuscripts stay intact.
const from: Record<string, string> = {
  antikythera: "남은 유물로 과거를 복원하는 과정을 읽었다면,",
  "frankenstein-ai": "만들 수 있다는 사실 뒤의 책임을 생각했다면,",
  eratosthenes: "작은 차이에서 전체를 추론하는 방법을 봤다면,",
  calendar: "자연의 주기와 사회의 시간을 나란히 봤다면,",
  longitude: "시계로 위치를 알아내는 과정을 읽었다면,",
  maps: "세계를 펼치는 방식이 시선을 바꾼다는 점을 봤다면,",
  relativity: "떨어진 시계의 시간을 비교하는 조건을 따졌다면,",
  telescope: "새로운 관측이 설명을 바꾸는 순간을 읽었다면,",
  microscope: "더 크게 보는 것과 이해하는 것의 차이를 봤다면,",
  evolution: "생명의 변화를 하나의 사다리로 보기 어렵다면,",
  mendel: "규칙적인 비율과 개별 생명의 차이를 생각했다면,",
  "periodic-table": "표에 남긴 빈칸이 예측을 돕는 과정을 봤다면,",
  entropy: "가능한 변화와 저절로 일어나는 변화를 구분했다면,",
  quantum: "입자의 경로와 도착 무늬를 설명하는 조건을 봤다면,",
  "plate-tectonics": "닮은 모양을 넘어서는 증거가 필요하다는 점을 봤다면,",
  "dna-code": "생명을 암호로 읽는 표현의 범위를 생각했다면,",
  printing: "문장이 복제되며 생각의 길이 바뀌는 과정을 봤다면,",
  "steam-work": "기계가 힘과 하루의 시간을 함께 바꾸는 모습을 봤다면,",
  electromagnetism: "다른 현상을 하나의 설명으로 묶는 과정을 읽었다면,",
  shannon: "정보를 세는 일과 의미를 이해하는 일을 구분했다면,",
  feedback: "목표를 잘 따르는 것과 좋은 목표의 차이를 생각했다면,",
  "programmable-weaving": "작업 순서가 기계의 명령으로 남는 과정을 봤다면,",
  "turing-computation": "계산으로 풀 수 있는 문제의 경계를 살폈다면,",
  "germ-theory": "원인을 설명하는 방식이 책임을 바꾸는 모습을 봤다면,",
  reproducibility: "결과를 다시 얻지 못했을 때 따질 조건을 봤다면,",
  "atomic-age": "가능해진 기술과 선택해야 할 일을 구분했다면,",
  "archives-silence": "남은 기록 밖의 목소리를 생각했다면,",
  earthrise: "지구를 바라보는 한 장의 사진이 남긴 질문을 봤다면,",
  "climate-ice": "현재의 측정으로 오래된 대기를 읽는 과정을 봤다면,",
  "model-limits": "모형이 설명할 수 있는 범위를 따졌다면,",
};
const to: Record<string, string> = {
  antikythera: "남은 유물과 재구성의 경계를 다른 사례에서 살펴봅니다.",
  "frankenstein-ai": "창조한 존재를 돌보는 책임을 프랑켄슈타인에서 이어 읽습니다.",
  eratosthenes: "그림자의 차이로 지구 전체를 추론한 방법을 따라갑니다.",
  calendar: "하늘의 주기와 사람의 약속이 만나는 달력을 들여다봅니다.",
  longitude: "바다 위의 시계가 위치를 알려 주는 조건을 살펴봅니다.",
  maps: "지도를 만드는 선택이 세계의 모습을 어떻게 바꾸는지 봅니다.",
  relativity: "서로 떨어진 곳의 시간을 함께 말하는 조건을 이어 짚습니다.",
  telescope: "망원경의 관측을 증거로 받아들이는 과정을 살펴봅니다.",
  microscope: "확대된 장면에서도 설명이 필요한 작은 세계로 들어갑니다.",
  evolution: "생명의 변화를 가지가 갈라지는 역사로 읽어 봅니다.",
  mendel: "완두콩의 비율에서 규칙을 찾아내는 과정을 살펴봅니다.",
  "periodic-table": "주기율표의 빈칸이 예측을 만드는 방식을 이어 봅니다.",
  entropy: "되돌리기 어려운 변화와 가능한 변화의 차이를 짚어 봅니다.",
  quantum: "관측 조건에 따라 달라지는 실험에서 설명의 조건을 짚어 봅니다.",
  "plate-tectonics": "대륙의 움직임을 뒷받침한 증거가 어떻게 모였는지 봅니다.",
  "dna-code": "DNA를 암호로 읽는 표현이 설명하는 것과 가리는 것을 봅니다.",
  printing: "인쇄가 문장을 나누는 방식과 생각의 길을 바꾼 과정을 읽습니다.",
  "steam-work": "증기기관이 일과 하루의 시간을 바꾼 과정을 따라갑니다.",
  electromagnetism: "전기와 자석을 하나의 설명으로 연결하는 과정을 살펴봅니다.",
  shannon: "의미를 잠시 내려놓고 정보의 양을 세는 방법을 살펴봅니다.",
  feedback: "되먹임이 따르는 목표를 누가 정하는지 이어 생각합니다.",
  "programmable-weaving": "직물의 무늬가 작업 명령으로 기록되는 모습을 봅니다.",
  "turing-computation": "기계가 계산할 수 있는 일의 경계를 이어 살펴봅니다.",
  "germ-theory": "보이지 않는 원인을 이해한 뒤 달라지는 책임을 살펴봅니다.",
  reproducibility: "다시 얻지 못한 결과를 설명하려면 무엇을 확인해야 하는지 봅니다.",
  "atomic-age": "핵기술의 탄생에서 연구자의 역할과 선택을 이어 짚습니다.",
  "archives-silence": "기록에 남은 목소리와 남지 않은 목소리의 차이를 읽습니다.",
  earthrise: "지구를 밖에서 본 사진이 시선을 바꾸는 과정을 살펴봅니다.",
  "climate-ice": "얼음 속 공기로 과거의 대기를 추론하는 방법을 따라갑니다.",
  "model-limits": "좋은 설명에도 적용되는 범위가 있다는 점을 다른 사례로 짚습니다.",
};
const connections: Record<string, string> = {
  "model-limits/antikythera": "모형의 설명 범위를 따진 뒤, 남은 유물과 재구성의 경계를 안티키테라에서 나란히 살펴봅니다.",
  "model-limits/quantum": "설명이 성립하는 조건을 더 파고들고 싶다면, 관측 조건에 따라 달라지는 이중 슬릿 실험을 이어 봅니다.",
  "model-limits/reproducibility": "모형의 예측을 검증하는 일로 넘어가, 같은 결과를 다시 얻지 못했을 때 확인할 조건을 짚습니다.",
  "earthrise/maps": "사진이 바꾼 시선을 살펴봤다면, 같은 지구를 평면에 옮긴 지도가 보여 주는 선택을 이어 읽습니다.",
  "earthrise/climate-ice": "지구 전체를 보는 시선에서 측정으로 옮겨 가, 얼음 속 공기로 과거의 대기를 읽는 방법을 살펴봅니다.",
  "earthrise/atomic-age": "한 행성을 함께 살아간다는 관점은, 핵기술을 둘러싼 연구자와 사회의 선택으로 이어집니다.",
  "frankenstein-ai/turing-computation": "만들 수 있는 존재의 책임을 생각한 뒤, 기계가 풀 수 있는 문제에는 어떤 경계가 있는지 봅니다.",
  "frankenstein-ai/feedback": "창조자의 돌봄을 시스템의 목표로 옮겨, 잘 조절되는 기계에도 목적을 따져야 하는 이유를 읽습니다.",
  "frankenstein-ai/atomic-age": "기술을 가능하게 한 사람들의 책임이라는 질문을, 핵기술의 탄생과 선택에서 이어 갑니다.",
  "antikythera/turing-computation": "고대 기계가 계산한 것을 살펴봤다면, 계산 가능한 문제와 기계의 한계를 튜링의 논의에서 짚습니다.",
  "antikythera/archives-silence": "남아 있는 물건으로 복원한 역사에서 한 걸음 더 가, 기록을 남기지 못한 사람들의 빈자리를 생각합니다.",
  "antikythera/model-limits": "안티키테라의 재구성이 남긴 빈칸을 바탕으로, 좋은 모형이 설명할 수 있는 범위를 따져 봅니다.",
};
export function readingBridge(source: string, target: string) {
  return connections[`${source}/${target}`] ?? (from[source] && to[target] ? `${from[source]} ${to[target]}` : "");
}
