import type { HealthArticle, HealthClaim, HealthSource, HealthTool } from "./content";

type Batch2Slug =
  | "allergic-rhinitis"
  | "gastroesophageal-reflux-disease"
  | "osteoarthritis"
  | "osteoporosis";

export const batch2HealthSources: HealthSource[] = [
  { id: "SRC-NIDDK-GI-BLEEDING", organization: "NIH/NIDDK", title: "Symptoms & Causes of GI Bleeding", url: "https://www.niddk.nih.gov/health-information/digestive-diseases/gastrointestinal-bleeding/symptoms-causes", sourceDate: "2024-07 (Last Reviewed)", retrievedAt: "2026-09-06" },
  { id: "SRC-MEDLINEPLUS-AR-QUESTIONS", organization: "NIH/MedlinePlus", title: "Allergic rhinitis - what to ask your doctor - adult", url: "https://medlineplus.gov/ency/patientinstructions/000247.htm", sourceDate: "2025-01-01 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-MEDLINEPLUS-ALLERGY-SKIN-TEST", organization: "NIH/MedlinePlus", title: "Allergy testing - skin", url: "https://medlineplus.gov/ency/article/003519.htm", sourceDate: "2026-01-20 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-MEDLINEPLUS-AR", organization: "NIH/MedlinePlus", title: "Allergic rhinitis", url: "https://medlineplus.gov/ency/article/000813.htm", sourceDate: "2026-01-20 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-MEDLINEPLUS-HAY", organization: "NIH/MedlinePlus", title: "Hay Fever", url: "https://medlineplus.gov/hayfever.html", sourceDate: "페이지 표시일 미확인", retrievedAt: "2026-09-06" },
  { id: "SRC-CDC-POLLEN", organization: "CDC", title: "Pollen and Your Health", url: "https://www.cdc.gov/climate-health/php/effects/pollen-health.html", sourceDate: "2026-08-11 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-SNUH-AR", organization: "서울대학교병원", title: "알레르기 비염", url: "https://www.snuh.org/health/nMedInfo/nView.do?category=DIS&medid=AA000395", sourceDate: "페이지 표시일 미확인", retrievedAt: "2026-09-06" },
  { id: "SRC-NHS-AR", organization: "NHS", title: "Allergic rhinitis", url: "https://www.nhs.uk/conditions/allergic-rhinitis/", sourceDate: "2026-01-08 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIDDK-GERD-DEFINITION", organization: "NIH/NIDDK", title: "Definition & Facts for GER & GERD", url: "https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/definition-facts", sourceDate: "2020-07 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIDDK-GERD-SYMPTOMS", organization: "NIH/NIDDK", title: "Symptoms & Causes of GER & GERD", url: "https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/symptoms-causes", sourceDate: "2020-07 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIDDK-GERD-DIAGNOSIS", organization: "NIH/NIDDK", title: "Diagnosis of GER & GERD", url: "https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/diagnosis", sourceDate: "2020-07 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIDDK-GERD-DIET", organization: "NIH/NIDDK", title: "Eating, Diet, & Nutrition for GER & GERD", url: "https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/eating-diet-nutrition", sourceDate: "2020-07 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-KDCA-GERD", organization: "질병관리청 국가건강정보포털", title: "위식도역류질환", url: "https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=2057", sourceDate: "2026-06-02 업데이트", retrievedAt: "2026-09-06" },
  { id: "SRC-NHS-GERD", organization: "NHS", title: "Heartburn and acid reflux", url: "https://www.nhs.uk/conditions/heartburn-and-acid-reflux/", sourceDate: "2023-11-20 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIAMS-OA", organization: "NIH/NIAMS", title: "Osteoarthritis", url: "https://www.niams.nih.gov/health-topics/osteoarthritis", sourceDate: "2023-09 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIAMS-OA-TREATMENT", organization: "NIH/NIAMS", title: "Osteoarthritis: Diagnosis, Treatment, and Steps to Take", url: "https://www.niams.nih.gov/health-topics/osteoarthritis/diagnosis-treatment-and-steps-to-take", sourceDate: "2023-09 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-CDC-OA", organization: "CDC", title: "Osteoarthritis", url: "https://www.cdc.gov/arthritis/osteoarthritis/index.html", sourceDate: "2024-01-26", retrievedAt: "2026-09-06" },
  { id: "SRC-CDC-ARTHRITIS-ACTIVITY", organization: "CDC", title: "About Physical Activity and Arthritis", url: "https://www.cdc.gov/arthritis/prevention/index.html", sourceDate: "2024-02-14", retrievedAt: "2026-09-06" },
  { id: "SRC-KDCA-OA", organization: "질병관리청 국가건강정보포털", title: "골관절염", url: "https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=1988", sourceDate: "2026-06-08 업데이트", retrievedAt: "2026-09-06" },
  { id: "SRC-NHS-SEPTIC-ARTHRITIS", organization: "NHS", title: "Septic arthritis", url: "https://www.nhs.uk/conditions/septic-arthritis/", sourceDate: "2023-03-23 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIAMS-OP", organization: "NIH/NIAMS", title: "Osteoporosis", url: "https://www.niams.nih.gov/health-topics/osteoporosis", sourceDate: "2022-12 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIAMS-OP-TREATMENT", organization: "NIH/NIAMS", title: "Osteoporosis: Diagnosis, Treatment, and Steps to Take", url: "https://www.niams.nih.gov/health-topics/osteoporosis/diagnosis-treatment-and-steps-to-take", sourceDate: "2022-12 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIAMS-BMD", organization: "NIH/NIAMS", title: "Bone Mineral Density Tests: What the Numbers Mean", url: "https://www.niams.nih.gov/health-topics/bone-mineral-density-tests-what-numbers-mean", sourceDate: "2025-02 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-NIAMS-BONE-HEALTH", organization: "NIH/NIAMS", title: "Bone Health and Osteoporosis", url: "https://www.niams.nih.gov/health-topics/bone-health-and-osteoporosis", sourceDate: "2025-03 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-KDCA-OP", organization: "질병관리청 국가건강정보포털", title: "골다공증", url: "https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5833", sourceDate: "2026-05-19 업데이트", retrievedAt: "2026-09-06" },
  { id: "SRC-NHS-HIP-FRACTURE", organization: "NHS", title: "Broken hip", url: "https://www.nhs.uk/conditions/broken-hip/", sourceDate: "2026-07-29 검토", retrievedAt: "2026-09-06" },
  { id: "SRC-MEDLINEPLUS-BLOOD-CALCIUM", organization: "NIH/MedlinePlus", title: "Calcium Blood Test", url: "https://medlineplus.gov/lab-tests/calcium-blood-test/", sourceDate: "2024-12-02 업데이트", retrievedAt: "2026-09-06" },
  { id: "SRC-ISCD-ADULT-POSITIONS", organization: "International Society for Clinical Densitometry", title: "Official Adult Positions", url: "https://iscd.org/official-positions-2023/", sourceDate: "2023-08-24 승인", retrievedAt: "2026-09-06" },
];

const claim = (
  id: string,
  articleSlug: Batch2Slug,
  section: string,
  text: string,
  type: HealthClaim["type"],
  sourceIds: string[],
  clinicalReviewRequired: boolean,
  wordingRisk: HealthClaim["wordingRisk"],
): HealthClaim => ({ id, articleSlug, section, text, type, sourceIds, clinicalReviewRequired, wordingRisk });

export const batch2HealthClaims: HealthClaim[] = [
  claim("AR-B2-001", "allergic-rhinitis", "definition", "알레르기 비염은 꽃가루·집먼지·동물 비듬처럼 알레르기 반응을 일으킬 수 있는 물질에 코가 반응하며 재채기, 맑은 콧물, 코막힘 같은 증상이 나타나는 상태입니다.", "DEFINITION", ["SRC-MEDLINEPLUS-AR", "SRC-MEDLINEPLUS-HAY"], false, "LOW"),
  claim("AR-B2-002", "allergic-rhinitis", "symptoms", "재채기, 맑은 콧물, 코막힘, 코·눈의 가려움과 눈물은 알레르기 비염에서 나타날 수 있지만, 이 목록만으로 원인을 확정할 수는 없습니다.", "SYMPTOM", ["SRC-MEDLINEPLUS-AR", "SRC-MEDLINEPLUS-HAY"], true, "MEDIUM"),
  claim("AR-B2-003", "allergic-rhinitis", "trigger", "사람마다 관련되는 계절·장소·환경이 다를 수 있어, 증상이 생긴 때와 장소를 관찰해 의료진과 이야기하는 것이 원인 추정에 도움이 될 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-MEDLINEPLUS-AR", "SRC-CDC-POLLEN"], false, "LOW"),
  claim("AR-B2-004", "allergic-rhinitis", "diagnosis-limit", "증상은 감기나 다른 코 질환과 겹칠 수 있으므로 웹페이지나 한 번의 증상만으로 알레르기 비염을 스스로 진단하지 않습니다.", "SELF_CARE_LIMIT", ["SRC-MEDLINEPLUS-AR"], true, "HIGH"),
  claim("AR-B2-005", "allergic-rhinitis", "observation", "관찰 기록에는 증상이 시작된 때, 있었던 장소, 눈 증상 여부, 수면과 이미 사용 중인 치료를 함께 적을 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-MEDLINEPLUS-AR", "SRC-MEDLINEPLUS-HAY"], false, "LOW"),
  claim("AR-B2-006", "allergic-rhinitis", "environment", "꽃가루나 실내 알레르기 유발 물질과의 관련성은 개인마다 달라서, 환경 변화가 나에게 맞는지 기록으로 확인하고 일괄적인 해결책으로 단정하지 않습니다.", "SELF_CARE_LIMIT", ["SRC-CDC-POLLEN", "SRC-MEDLINEPLUS-AR"], true, "MEDIUM"),
  claim("AR-B2-007", "allergic-rhinitis", "medicine-limit", "비강 스프레이나 알레르기 약의 선택과 사용법은 나이, 다른 질환과 복용 약에 따라 달라질 수 있어 제품을 임의로 시작·중단·변경하지 말고 의료진 또는 약사에게 확인합니다.", "SELF_CARE_LIMIT", ["SRC-MEDLINEPLUS-AR"], true, "HIGH"),
  claim("AR-B2-008", "allergic-rhinitis", "professional-help", "증상이 계속되거나 일상생활·수면에 영향을 주거나, 원인이 불확실하면 의료진과 상담해 다른 원인과 필요한 검사를 확인합니다.", "TREATMENT_OVERVIEW", ["SRC-MEDLINEPLUS-AR", "SRC-MEDLINEPLUS-HAY"], true, "MEDIUM"),
  claim("AR-B2-009", "allergic-rhinitis", "emergency", "숨쉬기 매우 어렵거나 의식이 흐려지는 등 위급한 변화가 있으면 비염으로 단정하거나 온라인 정보를 기다리지 말고 119에 도움을 요청합니다.", "EMERGENCY_SIGN", ["SRC-CDC-POLLEN", "SRC-KDCA-CPR"], true, "HIGH"),
  claim("AR-B2-010", "allergic-rhinitis", "family", "가족은 증상을 과장하거나 무시하지 않고, 당사자가 원할 때 기록 정리와 진료 질문 준비를 도울 수 있습니다.", "CAREGIVER_ACTION", ["SRC-MEDLINEPLUS-AR"], false, "LOW"),
  claim("AR-B2-011", "allergic-rhinitis", "questions", "진료에서는 증상 시기와 장소, 눈·호흡 증상, 사용 중인 약과 검사 필요 여부를 질문할 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-MEDLINEPLUS-AR", "SRC-MEDLINEPLUS-HAY"], false, "LOW"),
  claim("AR-B2-012", "allergic-rhinitis", "limit", "이 페이지의 체크리스트는 관찰과 질문 준비용이며 알레르기 원인을 확정하거나 치료 효과를 보장하지 않습니다.", "SELF_CARE_LIMIT", ["SRC-MEDLINEPLUS-AR"], true, "MEDIUM"),

  claim("GERD-B2-001", "gastroesophageal-reflux-disease", "definition", "위식도역류는 위 내용물이 식도로 올라오는 현상이며, 반복되어 불편하거나 합병증과 이어질 때 위식도역류질환이라고 부릅니다.", "DEFINITION", ["SRC-NIDDK-GERD-DEFINITION"], false, "LOW"),
  claim("GERD-B2-002", "gastroesophageal-reflux-disease", "symptoms", "속쓰림이나 내용물이 목·입 쪽으로 올라오는 느낌이 흔할 수 있고, 흉통·삼킴의 불편·기침·쉰 목소리처럼 다른 증상도 나타날 수 있습니다.", "SYMPTOM", ["SRC-NIDDK-GERD-SYMPTOMS"], true, "MEDIUM"),
  claim("GERD-B2-003", "gastroesophageal-reflux-disease", "diagnosis-limit", "속쓰림이나 흉부 불편이 있다고 해서 모두 역류는 아니며, 증상만으로 위식도역류질환을 스스로 진단하거나 다른 원인을 배제하지 않습니다.", "SELF_CARE_LIMIT", ["SRC-NIDDK-GERD-DIAGNOSIS", "SRC-NIDDK-GERD-SYMPTOMS"], true, "HIGH"),
  claim("GERD-B2-004", "gastroesophageal-reflux-disease", "observation", "기록에는 식사 시점, 눕거나 잠든 시점, 불편의 종류와 지속 시간, 삼킴 변화, 사용 중인 약과 메모를 함께 남길 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-NIDDK-GERD-DIAGNOSIS"], false, "LOW"),
  claim("GERD-B2-005", "gastroesophageal-reflux-disease", "individual-triggers", "어떤 음식·음료·식사 시간·자세가 증상과 관련되는지는 사람마다 다를 수 있으므로, 기록을 바탕으로 의료진과 개별적으로 확인합니다.", "SELF_CARE_LIMIT", ["SRC-NIDDK-GERD-DIET"], true, "MEDIUM"),
  claim("GERD-B2-006", "gastroesophageal-reflux-disease", "medicine-limit", "일반의약품을 포함한 약의 시작·중단·기간·용량은 다른 질환과 복용 약에 따라 달라질 수 있어 온라인 글만으로 결정하지 않습니다.", "SELF_CARE_LIMIT", ["SRC-NIDDK-GERD-SYMPTOMS", "SRC-NIDDK-GERD-DIAGNOSIS"], true, "HIGH"),
  claim("GERD-B2-007", "gastroesophageal-reflux-disease", "professional-help", "흉통, 지속되는 구토, 삼키기 어렵거나 아픈 증상, 출혈을 의심할 수 있는 구토·검은 변, 원인 없는 체중 감소는 의료진에게 확인해야 할 변화입니다.", "EMERGENCY_SIGN", ["SRC-NIDDK-GERD-SYMPTOMS"], true, "HIGH"),
  claim("GERD-B2-008", "gastroesophageal-reflux-disease", "emergency", "새롭고 심한 가슴 통증, 숨쉬기 어려움, 의식 저하처럼 위급한 변화가 있으면 역류로 단정하지 말고 119에 도움을 요청합니다.", "EMERGENCY_SIGN", ["SRC-NIDDK-GERD-SYMPTOMS", "SRC-KDCA-CPR"], true, "HIGH"),
  claim("GERD-B2-009", "gastroesophageal-reflux-disease", "family", "가족은 식사나 체형을 평가하기보다, 당사자가 원할 때 기록과 진료 질문을 정리하는 방식으로 도울 수 있습니다.", "CAREGIVER_ACTION", ["SRC-NIDDK-GERD-DIAGNOSIS"], false, "LOW"),
  claim("GERD-B2-010", "gastroesophageal-reflux-disease", "questions", "진료에서는 증상 시점, 누웠을 때의 변화, 삼킴 문제, 사용 중인 약, 검사 필요 여부를 질문할 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-NIDDK-GERD-DIAGNOSIS"], false, "LOW"),
  claim("GERD-B2-011", "gastroesophageal-reflux-disease", "care-limit", "이 페이지의 시간표와 체크리스트는 치료 처방이나 음식 금지 목록이 아니라, 개인 패턴을 의료진과 상의하기 위한 자료입니다.", "SELF_CARE_LIMIT", ["SRC-NIDDK-GERD-DIET", "SRC-NIDDK-GERD-DIAGNOSIS"], true, "MEDIUM"),
  claim("GERD-B2-012", "gastroesophageal-reflux-disease", "management", "생활 조정과 치료 방법은 증상·검사·다른 건강 상태에 따라 달라질 수 있어 개인 목표를 이 페이지가 정하지 않습니다.", "TREATMENT_OVERVIEW", ["SRC-NIDDK-GERD-DIAGNOSIS", "SRC-NIDDK-GERD-DIET"], true, "HIGH"),

  claim("OA-B2-001", "osteoarthritis", "definition", "골관절염은 관절 안의 연골과 다른 조직에 시간이 지나며 변화가 생기는 관절 질환입니다.", "DEFINITION", ["SRC-NIAMS-OA", "SRC-CDC-OA"], false, "LOW"),
  claim("OA-B2-002", "osteoarthritis", "symptoms", "관절을 쓸 때의 통증, 쉬고 난 뒤의 뻣뻣함, 움직임의 제한이나 부종은 골관절염에서 나타날 수 있지만 개인마다 양상이 다릅니다.", "SYMPTOM", ["SRC-NIAMS-OA", "SRC-CDC-OA"], true, "MEDIUM"),
  claim("OA-B2-003", "osteoarthritis", "diagnosis-limit", "관절 통증이나 소리만으로 골관절염을 스스로 확정하지 않으며, 의료진은 병력·진찰과 필요에 따라 다른 원인을 함께 확인합니다.", "SELF_CARE_LIMIT", ["SRC-NIAMS-OA-TREATMENT", "SRC-CDC-OA"], true, "HIGH"),
  claim("OA-B2-004", "osteoarthritis", "observation", "관찰 기록에는 불편한 관절, 활동 전후 변화, 부종·열감 여부, 수면과 일상에 미치는 영향, 사용 중인 치료를 적을 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-NIAMS-OA", "SRC-NIAMS-OA-TREATMENT"], false, "LOW"),
  claim("OA-B2-005", "osteoarthritis", "activity", "활동 계획은 관절 상태와 다른 건강 문제에 따라 달라질 수 있어, 새로운 운동이나 보조기구는 의료진 또는 재활 전문가와 안전한 범위를 상의합니다.", "TREATMENT_OVERVIEW", ["SRC-NIAMS-OA-TREATMENT", "SRC-CDC-ARTHRITIS-ACTIVITY"], true, "HIGH"),
  claim("OA-B2-006", "osteoarthritis", "medicine-limit", "진통제·주사·보조기구·수술 여부는 개인 치료 결정이므로 온라인 글이나 기록만으로 약을 스스로 시작·중단·변경하지 않습니다.", "SELF_CARE_LIMIT", ["SRC-NIAMS-OA-TREATMENT", "SRC-CDC-OA"], true, "HIGH"),
  claim("OA-B2-007", "osteoarthritis", "professional-help", "통증·부종·움직임 제한이 새롭게 생기거나 일상을 어렵게 하면 원인을 확인하기 위해 의료진에게 상담합니다.", "TREATMENT_OVERVIEW", ["SRC-NIAMS-OA", "SRC-NIAMS-OA-TREATMENT"], true, "MEDIUM"),
  claim("OA-B2-008", "osteoarthritis", "emergency", "심한 외상 뒤 움직일 수 없거나, 의식 저하·호흡곤란처럼 위급한 변화가 있으면 관절염으로 단정하거나 온라인 정보를 기다리지 말고 119에 도움을 요청합니다.", "EMERGENCY_SIGN", ["SRC-KDCA-CPR"], true, "HIGH"),
  claim("OA-B2-009", "osteoarthritis", "family", "가족은 속도를 재촉하거나 통증을 판단하기보다, 당사자가 원하는 일상 지원과 진료 질문 정리를 도울 수 있습니다.", "CAREGIVER_ACTION", ["SRC-NIAMS-OA-TREATMENT"], false, "LOW"),
  claim("OA-B2-010", "osteoarthritis", "questions", "진료에서는 어느 관절이 언제 불편한지, 활동·수면 변화, 다른 원인 확인, 안전한 활동 범위와 치료 선택지를 질문할 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-NIAMS-OA-TREATMENT"], false, "LOW"),
  claim("OA-B2-011", "osteoarthritis", "care-limit", "이 페이지의 활동 기록은 통증 점수로 병의 진행을 판단하거나 치료 효과를 보장하는 도구가 아닙니다.", "SELF_CARE_LIMIT", ["SRC-NIAMS-OA", "SRC-CDC-OA"], true, "MEDIUM"),
  claim("OA-B2-012", "osteoarthritis", "variation", "골관절염은 단순히 나이가 들어서 생기는 정상 변화로만 볼 수 없고, 증상과 영향은 사람마다 다를 수 있습니다.", "DEFINITION", ["SRC-NIAMS-OA", "SRC-CDC-OA"], false, "LOW"),

  claim("OP-B2-001", "osteoporosis", "definition", "골다공증은 뼈의 밀도·양 또는 구조와 강도가 변해 뼈가 약해지고 골절 위험이 커질 수 있는 질환입니다.", "DEFINITION", ["SRC-NIAMS-OP", "SRC-NIAMS-BMD"], false, "LOW"),
  claim("OP-B2-002", "osteoporosis", "silent", "골다공증은 증상이 없는 경우가 많아 골절이 생기기 전까지 알기 어려울 수 있습니다.", "SYMPTOM", ["SRC-NIAMS-OP"], false, "LOW"),
  claim("OP-B2-003", "osteoporosis", "risk", "나이, 일부 질환과 약, 생활 요인 등 여러 요소가 골다공증 위험과 관련될 수 있지만, 위험 요소 목록으로 개인의 질환을 판단하지 않습니다.", "RISK_FACTOR", ["SRC-NIAMS-OP"], true, "MEDIUM"),
  claim("OP-B2-004", "osteoporosis", "diagnosis", "골밀도 검사는 뼈의 밀도를 측정하는 검사이며, 결과 해석과 진단은 나이·다른 위험 요소를 함께 고려해 의료진이 합니다.", "TEST", ["SRC-NIAMS-BMD", "SRC-NIAMS-OP-TREATMENT"], true, "HIGH"),
  claim("OP-B2-005", "osteoporosis", "record", "진료 준비에는 이전 골절·낙상, 복용 약, 다른 질환, 검사 결과와 가족력을 포함해 의료진이 물어본 정보를 정리할 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-NIAMS-OP-TREATMENT", "SRC-NIAMS-OP"], false, "LOW"),
  claim("OP-B2-006", "osteoporosis", "fall-prevention", "집 안의 걸려 넘어질 수 있는 물건과 조명·통로를 살피는 일은 낙상 위험을 줄이기 위한 환경 점검의 한 부분이지만, 골절을 막는다고 보장하지는 않습니다.", "PREVENTION", ["SRC-NIAMS-OP-TREATMENT"], true, "MEDIUM"),
  claim("OP-B2-007", "osteoporosis", "medicine-limit", "골다공증 약의 시작·중단·변경과 칼슘·비타민D 보충 여부는 개인 상황에 따라 달라서 웹페이지나 검사 숫자만으로 스스로 결정하지 않습니다.", "SELF_CARE_LIMIT", ["SRC-NIAMS-OP-TREATMENT", "SRC-NIAMS-BONE-HEALTH"], true, "HIGH"),
  claim("OP-B2-008", "osteoporosis", "professional-help", "낙상 뒤 통증이 심하거나 움직이기 어렵거나, 새롭고 심한 등 통증·키 변화가 있으면 의료진에게 확인합니다.", "EMERGENCY_SIGN", ["SRC-NIAMS-OP"], true, "HIGH"),
  claim("OP-B2-009", "osteoporosis", "emergency", "낙상 뒤 의식이 흐려지거나 숨쉬기 어렵고 움직일 수 없을 만큼 위급한 변화가 있으면 온라인 정보를 기다리지 말고 119에 도움을 요청합니다.", "EMERGENCY_SIGN", ["SRC-KDCA-CPR"], true, "HIGH"),
  claim("OP-B2-010", "osteoporosis", "family", "가족은 낙상 위험을 비난하지 않고, 당사자 동의 아래 통로 점검·기록 정리·진료 질문 준비를 도울 수 있습니다.", "CAREGIVER_ACTION", ["SRC-NIAMS-OP-TREATMENT"], false, "LOW"),
  claim("OP-B2-011", "osteoporosis", "questions", "진료에서는 골밀도 검사 필요 여부와 결과 의미, 골절·낙상 이력, 복용 약, 개인에게 맞는 예방·치료 계획을 질문할 수 있습니다.", "MEASUREMENT_GUIDANCE", ["SRC-NIAMS-BMD", "SRC-NIAMS-OP-TREATMENT"], false, "LOW"),
  claim("OP-B2-012", "osteoporosis", "care-limit", "이 페이지의 집안 점검표와 용어 안내는 골다공증을 진단하거나 골절 위험을 계산하는 도구가 아닙니다.", "SELF_CARE_LIMIT", ["SRC-NIAMS-BMD", "SRC-NIAMS-OP"], true, "HIGH"),
];

export const batch2HealthArticles: Record<Batch2Slug, HealthArticle> = {
  "allergic-rhinitis": {
    slug: "allergic-rhinitis", title: "알레르기 비염, 감기와의 차이부터 검사·코 스프레이까지",
    seoTitle: "알레르기 비염 증상과 감기 차이, 검사·코 스프레이",
    publishedAt: "2026-08-26", updatedAt: "2026-09-06", sourceCheckedAt: "2026-09-06",
    eyebrow: "호흡·알레르기 · 코 증상과 원인 확인",
    description: "재채기·맑은 콧물만으로 감기와 알레르기 비염을 구분할 수 있을까요? 검사 양성의 의미, 코 스프레이 종류, 수면·환경 기록과 진료가 필요한 때를 정리합니다.",
    outcome: "코 증상의 패턴과 검사·약의 이름을 가져가, 원인과 나에게 맞는 사용법을 구체적으로 질문합니다.",
    summary: ["알레르기 비염은 특정 물질에 대한 알레르기 반응입니다. 모든 콧물이나 환경 자극이 알레르기인 것은 아닙니다.", "검사 양성만으로 원인을 확정하지 않고, 증상 시기·장소와 함께 해석합니다.", "코 스프레이는 종류별 역할과 사용 기간이 다릅니다. 숨쉬기 매우 어렵거나 의식이 흐려지면 기록보다 119가 먼저입니다."],
    sections: [
      { title: "감기일까요, 알레르기일까요?", paragraphs: ["맑은 콧물, 재채기, 코막힘은 여러 원인에서 겹칩니다. 코와 눈의 가려움이 함께 나타나거나 특정 계절·장소에서 반복되는 양상은 진료에 도움이 되는 단서이지, 혼자 병명을 고르는 기준은 아닙니다."],
        table: { caption: "코 증상을 이야기할 때 구분할 세 가지 — 자가진단표가 아닙니다", columns: ["가능한 원인", "알아둘 차이", "진료에 가져갈 단서"], rows: [
          ["알레르기 비염", "꽃가루·집먼지진드기 등 특정 물질에 대한 알레르기 반응", "노출 장소·계절과 코/눈 증상이 반복되는지"],
          ["감기 등 감염", "알레르기와 원인은 다르지만 코 증상이 겹칠 수 있음", "시작 시점, 열·목 불편 등 함께 생긴 변화"],
          ["비알레르기 비염", "알레르기 외에도 온도·습도 변화 등이 코를 자극할 수 있음", "어떤 상황에서 시작되고 얼마나 지속되는지"],
        ] }, claimIds: ["AR-B2-001", "AR-B2-002", "AR-B2-004"], sourceIds: ["SRC-SNUH-AR", "SRC-NHS-AR"], imageId: null,
      },
      { title: "꽃가루를 마셨다고 모두 같은 반응을 하는 것은 아닙니다", paragraphs: ["알레르기 비염에서는 나에게 알레르기를 일으키는 물질이 코 점막에 닿으며 면역 반응과 염증이 생깁니다. 원인 물질을 ‘알레르겐’이라고도 부릅니다. 꽃가루, 집먼지진드기, 곰팡이, 동물의 비듬 등이 관련될 수 있습니다.", "먼지처럼 보이는 모든 입자가 같은 알레르겐은 아닙니다. 담배 연기나 온도 변화처럼 증상을 자극하는 조건과 실제 알레르기 원인을 구분해야 합니다. 그림은 흡입과 코의 관계만 나타내며 반응의 정도나 치료 결과를 예측하지 않습니다."], claimIds: ["AR-B2-001", "AR-B2-003", "AR-B2-004"], sourceIds: ["SRC-SNUH-AR", "SRC-NHS-AR", "SRC-CDC-POLLEN"], imageId: "ar-explainer" },
      { title: "검사에서 양성이면 그 물질이 원인인가요?", paragraphs: ["필요하면 피부반응 검사나 특정 알레르겐에 대한 혈액검사를 합니다. 하지만 피부검사에서 양성인 물질이 모두 현재 코 증상의 원인인 것은 아닙니다. 실제 노출과 증상, 진찰 결과를 함께 봐야 합니다.", "검사 결과지와 함께 ‘언제, 어디서, 코와 눈에 무엇이 달라졌는지’를 가져가세요. 검사 전 약을 쉬어야 하는지 궁금해도 혼자 중단하지 말고 검사 기관에 약 이름을 알려 준비 지침을 확인합니다."], bullets: ["이 양성 결과가 제 증상 시기·장소와 맞나요?", "검사로 확인하지 못하는 다른 코 질환 가능성도 있나요?", "검사 전에 복용 약이나 스프레이를 어떻게 해야 하나요?"], claimIds: ["AR-B2-004", "AR-B2-007", "AR-B2-011"], sourceIds: ["SRC-SNUH-AR", "SRC-MEDLINEPLUS-AR"], imageId: null, links: [{ href: "/health/guides/reading-health-results", label: "결과지의 이상 표시와 재검 질문 정리" }] },
      { title: "코 스프레이, 모양보다 종류와 사용법을 확인하세요", paragraphs: ["스프레이라는 같은 형태라도 성분과 목적은 다릅니다. 먹는 항히스타민제도 졸림 등 주의점이 서로 다를 수 있습니다. 제품 이름·성분, 사용 횟수와 시작일을 적어 의료진 또는 약사에게 보여 주세요."],
        table: { caption: "코에 쓰는 제품을 확인할 때 물어볼 질문", columns: ["종류", "역할과 주의점", "확인할 질문"], rows: [
          ["비강 스테로이드", "코의 알레르기 염증을 조절하는 약; 정해진 사용법이 중요", "제게 맞는 분사 방법과 사용 기간은 무엇인가요?"],
          ["비충혈제거제", "코막힘을 줄이는 약; 권장 기간보다 오래 쓰면 코막힘이 악화될 수 있음", "이 제품의 최대 사용 기간과 이후 상담 기준은 무엇인가요?"],
          ["생리식염수 제품", "코 안을 씻거나 점액을 제거하는 데 사용; 약과 같은 역할은 아님", "제게 적절한 제품과 위생·사용 방법은 무엇인가요?"],
        ] }, claimIds: ["AR-B2-007", "AR-B2-012"], sourceIds: ["SRC-MEDLINEPLUS-AR", "SRC-NHS-AR", "SRC-MEDLINEPLUS-HAY"], imageId: null, links: [{ href: "/health/guides/medication-list", label: "약 이름과 실제 사용법을 목록으로 가져가기" }],
      },
      { title: "관찰표에는 청소 점수 대신 증상의 맥락을 남깁니다", paragraphs: ["같은 장소에서도 계절, 머문 시간, 이미 사용 중인 치료에 따라 상황이 다릅니다. ‘침실에서 눈이 가려웠다’처럼 사실을 적고, ‘집먼지진드기가 원인이다’라는 결론과 구분하세요. 기록을 모으느라 불편한 증상의 상담을 미룰 필요는 없습니다.", "꽃가루가 본인의 유발 요인이라면 예보가 높은 날 외출 시간을 조정하고, 외출 뒤 옷을 갈아입거나 씻는 방법을 고려할 수 있습니다. 집 안의 관련 물질을 줄이는 방법은 확인된 원인과 생활 여건에 맞춥니다. 환경 관리만으로 충분하지 않을 수 있으며, 불편이 남는 것을 가족 탓으로 돌리지 않습니다."], bullets: ["시작 시각·장소·활동: 증상 직전에 무엇을 했나요?", "코·눈·호흡·수면: 무엇이 달라져 일상에 불편했나요?", "약·환경 변화: 바꾼 날짜와 그 뒤 흐름은 어땠나요?"], claimIds: ["AR-B2-003", "AR-B2-005", "AR-B2-006", "AR-B2-010"], sourceIds: ["SRC-CDC-POLLEN", "SRC-NHS-AR", "SRC-MEDLINEPLUS-AR"], imageId: "ar-action", links: [{ href: "/health/tools/allergy-trigger-observation", label: "코·눈 증상과 장소 관찰표" }, { href: "/health/guides/symptom-journal", label: "관찰한 사실과 추측을 나눠 적는 법" }] },
      { title: "코 증상으로 진료받을 때 호흡과 수면도 말하세요", paragraphs: ["원인이 불확실하거나, 증상이 악화되거나, 수면·일상에 영향을 주거나, 기존 치료로 나아지지 않으면 진료를 예약합니다. 알레르기 비염과 천식이 함께 있는 사람도 있으므로 쌕쌕거림·기침·호흡 불편을 코막힘 탓으로만 넘기지 않습니다. 천식이 있고 평소보다 악화되면 의료진에게 신속히 알리세요."], claimIds: ["AR-B2-008", "AR-B2-011"], sourceIds: ["SRC-NHS-AR", "SRC-CDC-POLLEN"], imageId: null, links: [{ href: "/health/asthma", label: "천식의 호흡 증상과 개인 대처 계획" }, { href: "/health/tools/allergy-appointment-questions", label: "검사·스프레이를 묻는 진료 질문 카드" }] },
      { title: "숨쉬기 매우 어렵거나 의식이 흐려지면 119", paragraphs: ["심하게 숨쉬기 어렵거나 의식이 흐려지는 등 위급한 변화가 있으면 비염이라고 단정하지 말고 즉시 119에 도움을 요청합니다. 관찰표 작성이나 알레르기 검사 결과를 기다리지 않습니다. 단순 코막힘과 전신의 위급한 호흡·의식 변화는 같은 안내로 다루지 않습니다."], claimIds: ["AR-B2-009"], sourceIds: ["SRC-KDCA-CPR", "SRC-CDC-POLLEN"], tone: "warning", imageId: null, links: [{ href: "/health/guides/danger-signals", label: "위급할 때 먼저 할 행동과 119에 전할 내용" }] },
    ],
    faq: [
      { question: "맑은 콧물이면 감기가 아니라 알레르기인가요?", answer: "콧물 모양 하나로 구분할 수 없습니다. 가려움, 반복되는 계절·장소, 열이나 다른 변화 등을 함께 이야기하고 필요하면 진찰·검사를 받습니다.", claimIds: ["AR-B2-002", "AR-B2-004"], sourceIds: ["SRC-SNUH-AR", "SRC-NHS-AR"] },
      { question: "알레르기 검사 양성이 나온 것을 모두 피해야 하나요?", answer: "양성 결과만으로 현재 증상의 원인을 정하지 않습니다. 실제 노출과 증상이 맞는지 의료진과 해석한 뒤 생활에서 줄일 대상을 정합니다.", claimIds: ["AR-B2-004", "AR-B2-006"], sourceIds: ["SRC-SNUH-AR"] },
      { question: "코 스프레이는 모두 오래 쓰면 안 되나요?", answer: "종류를 구분해야 합니다. 비충혈제거제는 오래 쓰면 코막힘을 악화시킬 수 있고, 비강 스테로이드는 다른 역할의 약입니다. 제품 설명서와 처방을 확인하고 임의로 사용 기간을 늘리거나 중단하지 마세요.", claimIds: ["AR-B2-007"], sourceIds: ["SRC-MEDLINEPLUS-AR", "SRC-NHS-AR"] },
      { question: "코 세척에 수돗물을 그대로 써도 되나요?", answer: "그대로 쓰지 않습니다. 증류수·멸균수 또는 끓인 뒤 식힌 물을 사용하도록 안내됩니다. 적절한 식염수 제품과 기구 위생·방법은 제품 지침과 의료진 또는 약사에게 확인하세요. 이 페이지는 집에서 만드는 배합법을 제시하지 않습니다.", claimIds: ["AR-B2-007", "AR-B2-012"], sourceIds: ["SRC-MEDLINEPLUS-AR", "SRC-MEDLINEPLUS-HAY", "SRC-NHS-AR"] },
      { question: "봄이 아닌데도 알레르기 비염일 수 있나요?", answer: "꽃가루의 계절도 다양하고, 집먼지진드기 등 실내 물질은 계절과 무관하게 관련될 수 있습니다. 시기만으로 진단하거나 배제하지 않습니다.", claimIds: ["AR-B2-001", "AR-B2-003"], sourceIds: ["SRC-SNUH-AR", "SRC-MEDLINEPLUS-HAY"] },
      { question: "코가 막혀 잠을 못 자도 그냥 참아야 하나요?", answer: "수면과 일상에 영향을 주는 증상은 진료 상담 이유입니다. 코 증상 외에 기침·쌕쌕거림이나 호흡 불편도 말하고, 심한 호흡곤란이나 의식 변화는 즉시119 도움을 받습니다.", claimIds: ["AR-B2-008", "AR-B2-009"], sourceIds: ["SRC-NHS-AR", "SRC-CDC-POLLEN", "SRC-KDCA-CPR"] },
    ],
    sourceIds: ["SRC-SNUH-AR", "SRC-NHS-AR", "SRC-MEDLINEPLUS-AR", "SRC-MEDLINEPLUS-HAY", "SRC-CDC-POLLEN", "SRC-KDCA-CPR"], imageIds: ["ar-hero", "ar-explainer", "ar-action"], toolSlugs: ["allergy-trigger-observation", "allergy-environment-check", "allergy-appointment-questions"],
  },
  "gastroesophageal-reflux-disease": {
    slug: "gastroesophageal-reflux-disease", title: "역류질환과 식도염, 무엇이 다를까요?",
    seoTitle: "위식도역류질환 증상과 역류성 식도염 차이",
    publishedAt: "2026-08-26", updatedAt: "2026-09-06", sourceCheckedAt: "2026-09-06",
    eyebrow: "소화 · 역류의 의미와 증상 시간표",
    description: "역류·위식도역류질환·식도염의 차이를 구분하고 식사, 눕는 시간, 속쓰림을 함께 기록합니다. 검사·약에 관해 물을 질문, 흉통·삼킴 변화 때의 진료 경계를 살핍니다.",
    outcome: "결과지의 병명과 증상 시간표를 구분해 읽고, 필요한 검사·생활 조정·약 사용법을 질문합니다.",
    summary: ["역류는 현상, 위식도역류질환은 반복되는 불편이나 합병증을 다루는 질환, 식도염은 식도에 염증이 있는 상태를 뜻합니다.", "식사와 눕기·증상 시각을 함께 적으면 음식 하나만 탓하지 않고 상담할 수 있습니다.", "가슴 압박·숨참·식은땀 등으로 심근경색이 의심되면 역류인지 확인하느라 기다리지 말고119에 연락합니다."],
    sections: [
      { title: "가슴 불편을 먼저 역류라고 결론 내리지 마세요", paragraphs: ["새롭거나 평소와 다른 가슴 압박·통증, 숨참, 식은땀, 팔·턱 등으로 퍼지는 불편으로 심근경색이 의심되면 즉시119에 연락합니다. 심근경색은 증상이 가볍거나 오르내릴 수도 있으므로 ‘아주 심해질 때까지’ 기다리지 않습니다.", "심한 호흡곤란이나 의식 저하도119 도움이 먼저입니다. 위장약을 먹어 본 뒤 반응으로 원인을 가르거나, 시간표를 완성하느라 도움 요청을 미루지 않습니다."], claimIds: ["GERD-B2-003", "GERD-B2-008"], sourceIds: ["SRC-NHLBI-HEART-ATTACK-SYMPTOMS", "SRC-KDCA-CPR", "SRC-NIDDK-GERD-SYMPTOMS"], tone: "warning", imageId: null, links: [{ href: "/health/acute-myocardial-infarction", label: "심근경색 의심 신호와119 행동" }] },
      { title: "현상·질환·염증을 나누면 결과지가 덜 헷갈립니다", table: { caption: "역류와 식도염을 읽는 세 가지 말", columns: ["표현", "뜻", "이것만으로 정할 수 없는 것"], rows: [
        ["위식도역류(GER)", "위 내용물이 식도로 올라오는 현상; 가끔은 건강한 사람에게도 생김", "한 번의 역류가 곧 질환이라는 결론"],
        ["위식도역류질환(GERD)", "역류가 반복되어 불편하거나 합병증과 이어지는 질환", "모든 속쓰림의 원인이나 개인의 중증도"],
        ["역류성 식도염", "역류와 관련해 식도 점막에 염증이 생긴 상태", "역류질환이 있으면 누구나 식도염이 있다는 결론"],
      ] }, paragraphs: ["결과지에 식도염이 적혀 있다면 관찰된 소견과 치료·추적 계획을 확인합니다. 반대로 식도염 소견이 없다고 모든 역류 증상과 다른 원인을 이 페이지에서 배제할 수는 없습니다."], claimIds: ["GERD-B2-001", "GERD-B2-003"], sourceIds: ["SRC-KDCA-GERD", "SRC-NIDDK-GERD-DEFINITION", "SRC-NIDDK-GERD-DIAGNOSIS"], imageId: null, links: [{ href: "/health/guides/reading-health-results", label: "검사 소견과 다음 진료 질문 나누기" }] },
      { title: "위의 내용물이 식도 쪽으로 올라올 때", paragraphs: ["식도와 위 사이의 조임근과 횡격막은 위 내용물이 거꾸로 올라오는 것을 막는 데 관여합니다. 이 기능이 약해지거나 적절하지 않은 때 열리면 역류가 생길 수 있습니다. 그림의 세 장면은 이동 방향을 보여 주는 비유이지 누구나 거치는 악화 단계가 아닙니다.", "가슴 안쪽이 타는 듯하거나 신맛·쓴맛이 올라오는 느낌이 있을 수 있습니다. 기침이나 쉰 목소리가 동반되기도 하지만 이런 증상만으로 역류를 확정하지는 않습니다."], claimIds: ["GERD-B2-001", "GERD-B2-002", "GERD-B2-003"], sourceIds: ["SRC-KDCA-GERD", "SRC-NIDDK-GERD-SYMPTOMS"], imageId: "gerd-explainer" },
      { title: "음식 이름 옆에 식사·눕기·불편 시각을 적습니다", paragraphs: ["같은 음식을 먹어도 양, 시간, 자세와 상황은 다를 수 있습니다. 음식 하나를 영구 금지하기 전에 증상이 생긴 날과 생기지 않은 날의 차이를 상담 자료로 남겨 보세요. 가족은 당사자가 원할 때 기록을 도울 수 있지만 식사나 체형을 평가하지 않습니다."], table: { caption: "진료용 시간표에 남길 서로 다른 정보", columns: ["기록 지점", "적을 내용", "질문으로 바꾸기"], rows: [
        ["식사", "먹은 것·양·먹고 마신 시각", "특정 음식보다 양이나 시간이 관련되나요?"],
        ["자세와 수면", "눕거나 잠든 시각, 몸을 굽힌 활동", "식사와 눕기 간격을 어떻게 조정할까요?"],
        ["불편과 약", "느낌·지속 시간·삼킴 변화·실제 약 사용", "이 양상에 추가 검사나 약 확인이 필요한가요?"],
      ] }, claimIds: ["GERD-B2-004", "GERD-B2-005", "GERD-B2-009", "GERD-B2-010"], sourceIds: ["SRC-NIDDK-GERD-DIAGNOSIS", "SRC-NIDDK-GERD-DIET", "SRC-NHS-GERD"], imageId: "gerd-action", links: [{ href: "/health/tools/gerd-symptom-timing-log", label: "식사·자세·증상 시간 기록표" }] },
      { title: "모든 사람이 곧바로 내시경을 받는 것은 아닙니다", paragraphs: ["의료진은 증상과 병력을 먼저 보고 치료나 검사의 필요성을 정합니다. 합병증·다른 원인이 의심되거나 치료 후에도 좋아지지 않으면 검사를 고려할 수 있습니다. 내시경은 점막과 다른 문제를 살피고, 식도 산도 검사는 산 역류와 증상의 관계를 확인하는 데 쓰입니다."], bullets: ["지금 검사로 확인하려는 것은 염증인가요, 역류와 증상의 관계인가요?", "우선 치료하며 볼 경우 언제 결과를 다시 평가하나요?", "검사 전 식사와 복용 약에 대한 기관의 준비 지침은 무엇인가요?"], claimIds: ["GERD-B2-003", "GERD-B2-010", "GERD-B2-012"], sourceIds: ["SRC-NIDDK-GERD-DIAGNOSIS"], imageId: null, links: [{ href: "/health/tools/gerd-appointment-prep", label: "위식도역류 검사·치료 질문 카드" }] },
      { title: "생활 조정과 약의 역할을 따로 확인합니다", paragraphs: ["밤이나 누웠을 때 증상이 있다면 눕기 최소 3시간 전에 식사를 마치는 방법이 도움이 될 수 있다는 안내가 있습니다. 누구에게나 같은 효과를 약속하는 규칙은 아니며 생활 여건과 개인 증상을 상담합니다. 증상을 유발하는 음식·음료는 개인마다 달라 공통 금지 목록을 만들지 않습니다.", "제산제 등 단기 증상 완화 약과 위산 분비를 줄이는 PPI는 역할과 사용 계획이 다릅니다. 일반의약품도 장기간 반복 복용하기 전에 확인하고, 처방약을 혼자 중단하거나 용량을 바꾸지 않습니다. 약 이름·시작일·사용법을 가져가 언제 다시 평가할지 물어보세요."], claimIds: ["GERD-B2-005", "GERD-B2-006", "GERD-B2-011", "GERD-B2-012"], sourceIds: ["SRC-NIDDK-GERD-DIET", "SRC-NHS-GERD"], imageId: null, links: [{ href: "/health/guides/medication-list", label: "일반의약품까지 복용약 목록에 정리" }] },
      { title: "시간표보다 진료 확인을 앞세울 변화", paragraphs: ["삼키기 어렵거나 아프거나, 구토가 계속되거나, 이유 없이 체중이 줄면 기록을 더 모으려고 기다리지 말고 의료진에게 알립니다. 피가 섞이거나 커피 찌꺼기처럼 보이는 구토, 검고 타르 같은 변도 바로 의료 도움을 구할 변화입니다.", "속쓰림이 자주 반복되거나 생활 조정·약국 약으로 나아지지 않는 경우에도 진료로 원인을 확인합니다. 이 목록은 모든 위험을 배제하는 검사표가 아닙니다. 위에서 설명한 심장 의심·호흡·의식의 위급한 변화는119가 먼저입니다."], claimIds: ["GERD-B2-007", "GERD-B2-008"], sourceIds: ["SRC-NIDDK-GERD-SYMPTOMS", "SRC-NHS-GERD", "SRC-NHLBI-HEART-ATTACK-SYMPTOMS"], imageId: null, links: [{ href: "/health/guides/danger-signals", label: "응급 도움과 진료 상담의 경계" }] },
    ],
    faq: [
      { question: "위식도역류질환과 역류성 식도염은 같은 뜻인가요?", answer: "완전히 같은 말은 아닙니다. 역류질환은 반복되는 불편이나 합병증을 다루고, 식도염은 식도 점막의 염증을 말합니다. 검사 소견과 증상을 함께 해석합니다.", claimIds: ["GERD-B2-001", "GERD-B2-003"], sourceIds: ["SRC-KDCA-GERD", "SRC-NIDDK-GERD-DEFINITION"] },
      { question: "가슴이 쓰리면 위장약부터 먹어 보면 되나요?", answer: "새롭거나 평소와 다른 가슴 불편을 약 반응으로 진단하지 않습니다. 심근경색이 의심되거나 호흡·의식이 위급하면 약 효과를 기다리지 말고119에 연락합니다.", claimIds: ["GERD-B2-003", "GERD-B2-008"], sourceIds: ["SRC-NHLBI-HEART-ATTACK-SYMPTOMS", "SRC-KDCA-CPR"] },
      { question: "커피나 매운 음식은 평생 끊어야 하나요?", answer: "증상을 유발하는 음식·음료는 사람마다 다릅니다. 먹은 양과 시각, 눕기와 증상의 관계를 기록해 조정할 대상을 상담하며 이 글이 영구 금지 목록을 정하지 않습니다.", claimIds: ["GERD-B2-005", "GERD-B2-011"], sourceIds: ["SRC-NIDDK-GERD-DIET"] },
      { question: "증상이 있으면 내시경을 반드시 하나요?", answer: "증상과 병력으로 먼저 평가하기도 합니다. 합병증이나 다른 원인이 의심되는지, 치료 반응이 어떤지에 따라 검사 목적과 필요성을 의료진이 정합니다.", claimIds: ["GERD-B2-003", "GERD-B2-010"], sourceIds: ["SRC-NIDDK-GERD-DIAGNOSIS"] },
      { question: "기침이나 쉰 목소리만 있어도 역류인가요?", answer: "역류와 함께 나타날 수 있지만 원인은 다양합니다. 목·호흡 증상만으로 결론 내리지 말고 다른 가능성도 확인합니다.", claimIds: ["GERD-B2-002", "GERD-B2-003"], sourceIds: ["SRC-NIDDK-GERD-SYMPTOMS", "SRC-KDCA-GERD"] },
      { question: "약을 먹고 좋아졌다가 다시 불편하면 용량을 늘리나요?", answer: "임의로 늘리거나 오래 반복 복용하지 말고 증상이 돌아온 시점과 실제 복용법을 알려 재평가받습니다. 개인의 처방 계획은 이 글로 바꾸지 않습니다.", claimIds: ["GERD-B2-006", "GERD-B2-012"], sourceIds: ["SRC-NHS-GERD"] },
    ],
    sourceIds: ["SRC-KDCA-GERD", "SRC-NIDDK-GERD-DEFINITION", "SRC-NIDDK-GERD-SYMPTOMS", "SRC-NIDDK-GERD-DIAGNOSIS", "SRC-NIDDK-GERD-DIET", "SRC-NHS-GERD", "SRC-NHLBI-HEART-ATTACK-SYMPTOMS", "SRC-KDCA-CPR"], imageIds: ["gerd-hero", "gerd-explainer", "gerd-action"], toolSlugs: ["gerd-symptom-timing-log", "gerd-everyday-patterns", "gerd-appointment-prep"],
  },
  osteoarthritis: {
    slug: "osteoarthritis", seoTitle: "골관절염 증상과 운동, 무릎·손 관절 기록법", title: "골관절염, 통증과 일상 변화를 함께 살피기", eyebrow: "뼈·관절 · 활동과 진료 준비", description: "무릎·손·고관절의 통증과 달라진 일상을 함께 기록합니다. 골관절염의 검사·운동·치료 질문과 갑자기 붓고 아픈 관절의 진료 신호를 구분합니다.", outcome: "통증이 생기는 활동과 어려워진 일을 골라 기록하고, 내게 맞는 운동·검사·치료 계획을 질문합니다.",
    publishedAt: "2026-08-26", updatedAt: "2026-09-06", sourceCheckedAt: "2026-09-06",
    summary: ["골관절염은 연골만이 아니라 관절 전체의 조직에 변화가 생기는 질환입니다.", "아픈 정도와 함께 걷기·손 사용·수면이 어떻게 달라졌는지 알려주세요.", "갑자기 심하게 아프고 붓는 관절은 평소 관절염으로 넘기지 말고 신속히 진료받습니다."],
    sections: [
      { title: "어떤 일이 전보다 어려워졌나요?", paragraphs: ["진료에서 ‘무릎이 아파요’에 더해 ‘계단을 내려갈 때 멈춰 쉬어요’처럼 달라진 일을 말하면 생활에 미치는 영향을 전달하기 쉽습니다. 통증을 참거나 낮춰 말할 필요는 없습니다. 아픈 정도, 시작 시점, 부은 느낌, 쉬고 난 뒤의 뻣뻣함도 함께 알려주세요."], table: { caption: "관절별로 떠올려 볼 일상 변화 — 진단표가 아닌 기록 예시", columns: ["불편한 곳", "살펴볼 활동", "진료에 가져갈 메모"], rows: [["무릎", "걷기, 계단, 의자에서 일어서기", "어떤 동작에서 아픈지, 쉬어야 했는지, 불안정한 느낌이 있었는지"], ["손가락·엄지", "병뚜껑 열기, 단추 채우기, 물건 잡기", "어느 손·손가락인지, 힘주거나 움직일 때 무엇이 어려웠는지"], ["고관절 주변", "걷기, 신발·양말 신기", "불편을 느낀 위치와 움직임, 수면·외출에 미친 영향"]] }, claimIds: ["OA-B2-002", "OA-B2-004"], sourceIds: ["SRC-NIAMS-OA", "SRC-NIAMS-OA-TREATMENT"], imageId: null, links: [{ href: "/health/tools/oa-daily-activity-log", label: "관절 일상 변화 기록표 열기" }] },
      { title: "연골만 닳는 병, 나이 들면 당연한 병일까요?", paragraphs: ["골관절염은 뼈 끝을 덮는 연골뿐 아니라 뼈와 관절을 둘러싼 여러 조직에 변화가 생기는 질환입니다. 무릎·손·고관절 등에 생길 수 있으며, 관절을 쓸 때 아프거나 쉬었다 움직일 때 뻣뻣하고 부을 수 있습니다.", "나이가 들수록 흔하지만 정상 노화와 같은 뜻은 아닙니다. 이전 관절 손상 등 여러 요인이 관련되고 젊은 사람에게도 생길 수 있습니다. 통증이나 관절 소리만으로 병명을 정하지 않는 이유입니다. 아래 그림은 관절의 개념이며 내 연골 두께나 병의 단계를 보여 주지 않습니다."], claimIds: ["OA-B2-001", "OA-B2-002", "OA-B2-003", "OA-B2-012"], sourceIds: ["SRC-KDCA-OA", "SRC-NIAMS-OA", "SRC-CDC-OA"], imageId: "oa-explainer" },
      { title: "갑자기 붓고 심하게 아프면 기록보다 진료", paragraphs: ["한 관절이 갑자기 심하게 아프거나 붓고 뜨거워지는 변화는 평소 골관절염 때문이라고 넘기지 말고 당일 신속히 진료받으세요. 특히 발열·오한·몸이 많이 아픈 느낌이 함께 있으면 관절 감염 같은 원인을 빨리 확인해야 합니다. 열이 날 때까지 기다리는 기준이 아닙니다.", "심한 외상 뒤 움직일 수 없거나 의식 저하·호흡곤란처럼 위급한 변화가 있으면 119에 도움을 요청합니다. 급한 변화를 기록표로 관찰하며 기다리지 마세요. 평소 통증이라도 새로 생겼거나 계속되어 수면과 일상을 어렵게 한다면 진료에서 원인을 확인합니다."], claimIds: ["OA-B2-007", "OA-B2-008"], sourceIds: ["SRC-NHS-SEPTIC-ARTHRITIS", "SRC-KDCA-CPR", "SRC-NIAMS-OA-TREATMENT"], tone: "warning", imageId: null, links: [{ href: "/health/gout", label: "통풍과 요산 수치도 증상만으로 확정하지 않기" }] },
      { title: "진찰과 X선·MRI는 무엇을 확인하나요?", paragraphs: ["골관절염을 한 가지 검사만으로 확인하는 것은 아닙니다. 의료진은 어느 관절이 언제부터 불편했는지, 활동과의 관계, 이전 손상·질환·치료를 묻고 관절을 살핍니다. 관절염의 다른 원인이 의심되면 혈액이나 관절액 검사 등을 선택할 수 있습니다.", "X선은 뼈와 관절 간격 등의 변화를 보는 데 쓰지만 초기 변화가 모두 보이지는 않습니다. MRI는 필요한 경우 연골 등 다른 조직을 더 살피는 검사이지, 관절이 아픈 모든 사람에게 먼저 필요한 검사는 아닙니다. ‘어떤 가능성을 확인하려는 검사인가요?’라고 물어보세요."], claimIds: ["OA-B2-003", "OA-B2-010"], sourceIds: ["SRC-NIAMS-OA-TREATMENT", "SRC-KDCA-OA"], imageId: null, links: [{ href: "/health/guides/appointment-questions", label: "검사 목적과 다음 진료 질문 정리하기" }] },
      { title: "운동과 휴식은 내 반응을 보며 조정합니다", paragraphs: ["골관절염이 있다고 활동을 모두 멈추는 것이 기본 원칙은 아닙니다. 자신에게 맞는 신체활동은 통증·뻣뻣함과 일상 기능을 돕습니다. 관절 움직임, 근력, 균형을 위한 운동과 걷기·자전거·물속 운동 등은 목적과 부담이 서로 다릅니다.", "처음에는 천천히 시작하고 반응을 살펴 시간·종류를 조정합니다. ‘아파도 무조건 걸어야 한다’거나 특정 걸음 수를 채워야 한다는 뜻은 아닙니다. 통증이 심하거나 가라앉지 않으면 의료진에게 알리고, 급격한 부종·열감은 위의 신속 진료 안내를 따릅니다."], bullets: ["시작 전: 내가 다시 편하게 하고 싶은 활동 하나와 현재 어려움을 적습니다.", "활동 뒤: 무엇을 얼마나 했고 통증·뻣뻣함·피로가 어떻게 달라졌는지 남깁니다.", "다음 상담: 내게 맞는 운동 종류·범위와 통증이 생겼을 때의 조정 기준을 확인합니다."], claimIds: ["OA-B2-004", "OA-B2-005", "OA-B2-011"], sourceIds: ["SRC-CDC-ARTHRITIS-ACTIVITY", "SRC-NIAMS-OA-TREATMENT"], imageId: null },
      { title: "약·보조도구는 생활 목표와 함께 질문하세요", paragraphs: ["치료의 목표에는 통증을 덜고 관절 기능과 생활을 유지하는 일이 함께 들어갑니다. 바르거나 먹는 약, 재활, 보조도구, 주사와 수술은 같은 역할이 아니며 모든 사람에게 같은 순서로 필요한 것도 아닙니다. 증상과 다른 건강 상태에 따라 선택을 상의합니다.", "약 이름뿐 아니라 실제 사용 방법과 불편했던 반응을 가져가세요. 진통제 등을 인터넷 정보로 스스로 시작·중단·증량하지 않고, 다른 처방약·일반의약품과 함께 써도 되는지 의료진이나 약사에게 확인합니다. 지팡이·보조기도 몸과 용도에 맞게 선택하고 사용하는 법을 배웁니다."], bullets: ["이 치료로 무엇이 좋아지는지, 효과와 불편은 언제 다시 평가하나요?", "계단·손 사용 등 제가 원하는 활동에 도움이 되는 재활이나 보조도구가 있나요?", "다른 치료를 검토해야 하는 변화와 다음 진료 시점은 무엇인가요?"], claimIds: ["OA-B2-005", "OA-B2-006", "OA-B2-010"], sourceIds: ["SRC-NIAMS-OA-TREATMENT", "SRC-KDCA-OA"], imageId: null, links: [{ href: "/health/guides/medication-list", label: "복용약·일반의약품 목록 준비하기" }, { href: "/health/tools/oa-visit-questions", label: "골관절염 진료 질문 카드" }] },
      { title: "가족에게는 필요한 도움을 골라 부탁합니다", paragraphs: ["가족은 ‘더 걸어야 해’라고 재촉하거나 겉모습으로 통증을 판단하기보다 어떤 일을 도와주면 좋을지 먼저 묻습니다. 물건 잡기나 이동의 어려움, 진료 동행과 기록 정리 중 당사자가 원하는 도움을 고릅니다. 모든 활동을 대신할지, 함께할지도 동의 아래 정합니다.", "같은 일을 전보다 편하게 했는지 알아보는 기록은 대화에 도움이 되지만 병의 진행이나 치료 효과를 판정하는 점수표는 아닙니다. 가족이 약이나 보조기구를 대신 결정하지 않습니다."], claimIds: ["OA-B2-009", "OA-B2-011"], sourceIds: ["SRC-NIAMS-OA-TREATMENT"], imageId: "oa-action", links: [{ href: "/health/tools/oa-family-support", label: "관절 불편 가족 지원 체크" }] },
    ],
    faq: [
      { question: "무릎에서 소리가 나면 골관절염인가요?", answer: "소리 하나로 진단하지 않습니다. 통증·부종·움직임과 병력을 함께 진찰해 원인을 확인합니다. 새로 아프거나 생활이 불편해졌다면 그 변화를 알려주세요.", claimIds: ["OA-B2-003", "OA-B2-007"], sourceIds: ["SRC-NIAMS-OA-TREATMENT", "SRC-KDCA-OA"] },
      { question: "나이가 들면 당연히 생겨서 치료할 필요가 없나요?", answer: "골관절염은 정상 노화와 같은 뜻이 아닙니다. 증상을 줄이고 기능을 유지할 방법을 상담할 수 있으므로 나이 탓으로 참기만 하지 않습니다.", claimIds: ["OA-B2-012", "OA-B2-007"], sourceIds: ["SRC-CDC-OA", "SRC-NIAMS-OA-TREATMENT"] },
      { question: "관절이 아프면 운동을 모두 쉬어야 하나요?", answer: "전부 쉬기보다 상태에 맞는 활동과 휴식 계획을 세웁니다. 천천히 시작해 반응을 보고 조정하되, 심하거나 가라앉지 않는 통증은 의료진에게 알립니다. 갑작스러운 심한 통증·부종은 먼저 신속히 진료받습니다.", claimIds: ["OA-B2-005", "OA-B2-007"], sourceIds: ["SRC-CDC-ARTHRITIS-ACTIVITY", "SRC-NHS-SEPTIC-ARTHRITIS"] },
      { question: "X선에 변화가 없으면 괜찮고 MRI는 꼭 해야 하나요?", answer: "초기 변화가 X선에 모두 보이지는 않습니다. 반대로 모든 관절 통증에 MRI가 필요한 것도 아닙니다. 진찰 결과와 확인하려는 문제에 따라 필요한 검사를 상의합니다.", claimIds: ["OA-B2-003", "OA-B2-010"], sourceIds: ["SRC-NIAMS-OA-TREATMENT"] },
      { question: "손가락에도 골관절염이 생길 수 있나요?", answer: "생길 수 있습니다. 손가락 끝이나 엄지 주변 등에도 나타날 수 있어 어느 손가락이 어떤 일을 할 때 불편한지 적습니다. 손 통증의 다른 원인도 있어 위치만으로 확정하지는 않습니다.", claimIds: ["OA-B2-001", "OA-B2-003", "OA-B2-004"], sourceIds: ["SRC-NIAMS-OA", "SRC-NIAMS-OA-TREATMENT"] },
      { question: "한 관절이 갑자기 붓고 뜨거워졌는데 다음 예약까지 기다려도 되나요?", answer: "평소 골관절염으로 넘기지 말고 당일 신속히 진료받으세요. 특히 심한 통증이나 발열·오한·전신 불편이 있으면 감염 등 다른 원인의 빠른 확인이 필요합니다. 모든 증상이 함께 생길 때까지 기다리지 않습니다.", claimIds: ["OA-B2-007", "OA-B2-008"], sourceIds: ["SRC-NHS-SEPTIC-ARTHRITIS"] },
    ],
    sourceIds: ["SRC-KDCA-OA", "SRC-NIAMS-OA", "SRC-NIAMS-OA-TREATMENT", "SRC-CDC-OA", "SRC-CDC-ARTHRITIS-ACTIVITY", "SRC-NHS-SEPTIC-ARTHRITIS", "SRC-KDCA-CPR"], imageIds: ["oa-hero", "oa-explainer", "oa-action"], toolSlugs: ["oa-daily-activity-log", "oa-visit-questions", "oa-family-support"],
  },
  osteoporosis: {
    slug: "osteoporosis", seoTitle: "골다공증과 골밀도 검사: T점수·Z점수 뜻과 낙상 예방", title: "골다공증, 검사표와 낙상 예방을 함께 보기", eyebrow: "뼈 건강 · 검사와 골절 예방", description: "골밀도 검사의 DXA·T점수·Z점수와 혈중 칼슘 검사를 구분합니다. 골절·약 이력과 집안 점검을 준비하고, 낙상 뒤 즉시 도움이 필요한 신호를 확인합니다.", outcome: "검사표의 용어와 확인할 이력을 골라 질문하고, 낙상 뒤에는 기록보다 응급 도움이 먼저인지 구분합니다.",
    publishedAt: "2026-08-26", updatedAt: "2026-09-06", sourceCheckedAt: "2026-09-06",
    summary: ["골다공증은 골절 전까지 별다른 증상이 없을 수 있어 아프지 않다는 것만으로 알 수 없습니다.", "T점수·Z점수는 비교 기준이 다릅니다. 진단과 치료는 골절 이력 등 개인 상황을 함께 봅니다.", "낙상 뒤 심한 고관절 통증이나 다리에 체중을 싣지 못하는 변화는 의식이 또렷해도 119에 도움을 요청합니다."],
    sections: [
      { title: "아프지 않은데 검사에서 발견될 수 있나요?", paragraphs: ["골다공증은 뼈의 양과 구조·강도가 달라져 골절 위험이 커지는 질환입니다. 뼈가 부러지기 전까지 특별한 증상을 못 느끼는 경우가 많습니다. 반대로 허리나 무릎이 아프다고 모두 골다공증인 것도 아닙니다.", "척추·고관절·손목 등에 골절이 생길 수 있고, 작은 충격이나 일상 동작에서도 골절이 생기는 경우가 있습니다. 새롭고 심한 등 통증이나 키·자세의 변화가 있다면 진료에서 확인합니다. 그림 속 뼈는 구조 차이의 개념이지 내 검사 결과나 앞으로의 진행을 보여 주는 것이 아닙니다."], claimIds: ["OP-B2-001", "OP-B2-002", "OP-B2-008"], sourceIds: ["SRC-NIAMS-OP", "SRC-KDCA-OP"], imageId: "op-explainer" },
      { title: "검사표에서 DXA·T점수·Z점수를 구분하기", paragraphs: ["골밀도는 뼈에 들어 있는 칼슘 등 무기질의 밀도를 측정한 정보입니다. 흔히 쓰는 DXA 검사는 X선을 이용해 척추와 고관절 등의 골밀도를 살핍니다. 아래 표는 용어 안내이며 개인 숫자를 진단하는 표가 아닙니다."], table: { caption: "검사 이름과 비교 기준은 서로 다른 정보입니다", columns: ["표시", "무엇을 뜻하나요?", "결과를 볼 때 질문"], rows: [["DXA 또는 DEXA", "골밀도를 측정하는 검사 방법", "언제, 어느 부위를 측정했나요?"], ["T점수 / T-score", "젊은 성인 기준의 골밀도와 비교한 값", "제 상태에는 이 비교 기준을 적용하나요?"], ["Z점수 / Z-score", "연령·성별 등을 고려한 기준과 비교한 값", "연령에 비해 낮다면 다른 원인도 확인하나요?"], ["혈중 칼슘", "혈액 속 칼슘을 측정한 값", "골밀도 검사와 별도로 무엇을 확인하나요?"]] }, claimIds: ["OP-B2-004", "OP-B2-012"], sourceIds: ["SRC-NIAMS-BMD", "SRC-MEDLINEPLUS-BLOOD-CALCIUM"], imageId: null, links: [{ href: "/health/guides/reading-health-results", label: "검사표의 이름·단위·설명 함께 읽기" }] },
      { title: "같은 숫자라도 누구의 결과인지가 중요합니다", paragraphs: ["일반적으로 폐경 후 여성과 50세 이상 남성의 골밀도 보고에는 T점수를, 폐경 전 여성과 50세 미만 남성에는 Z점수를 우선 사용합니다. Z점수는 소아에서도 사용합니다. 결과지에 보이는 점수만 골라 적용하지 말고 의료진에게 본인에게 맞는 기준을 확인하세요.", "골밀도가 연령에 비해 낮다는 설명과 골다공증 확정 진단은 같은 말이 아닙니다. 나이, 폐경 여부, 이전 골절, 일부 질환과 약 등도 함께 평가합니다. 혈중 칼슘이 정상이어도 그것만으로 뼈의 밀도나 뼛속 칼슘량을 알 수는 없습니다."], claimIds: ["OP-B2-003", "OP-B2-004", "OP-B2-012"], sourceIds: ["SRC-ISCD-ADULT-POSITIONS", "SRC-KDCA-OP", "SRC-NIAMS-BMD", "SRC-MEDLINEPLUS-BLOOD-CALCIUM"], imageId: null },
      { title: "낙상 뒤 의식이 또렷해도 119가 필요할 수 있습니다", paragraphs: ["넘어지거나 다친 뒤 엉덩이·사타구니 부위가 심하게 아프거나, 걷지 못하거나 다리에 체중을 실을 수 없다면 119에 도움을 요청합니다. 의식이 흐려질 때까지 기다리지 마세요. 다친 뒤 고관절·다리의 감각이 없어지거나 저리는 변화도 즉시 응급 도움을 받습니다.", "직접 운전하지 말고 119의 안내를 따릅니다. 의식 저하나 호흡곤란이 있으면 역시 즉시 119입니다. 검사표나 약 목록을 찾느라 신고를 늦추지 않습니다. 낙상 뒤 고관절 통증은 골절 가능성을 신속히 확인해야 하므로 가벼워 보여도 진료를 미루지 마세요."], claimIds: ["OP-B2-008", "OP-B2-009"], sourceIds: ["SRC-NHS-HIP-FRACTURE", "SRC-KDCA-CPR"], tone: "warning", imageId: null, links: [{ href: "/health/guides/danger-signals", label: "온라인 정보보다 응급 도움이 먼저인 신호" }] },
      { title: "진료에는 검사 숫자와 이력을 함께 가져갑니다", paragraphs: ["골밀도 수치만 다시 적기보다 검사 날짜·기관·측정부위가 보이는 결과지를 준비합니다. 예전에 뼈가 부러졌다면 언제, 어느 부위였고 어떤 상황이었는지 알려주세요. 최근 넘어짐이나 균형 변화도 진료에서 함께 확인할 정보입니다."], bullets: ["이력: 이전 골절·낙상, 키나 자세의 변화, 관련 질환과 가족력.", "약: 처방약·일반의약품·보충제의 실제 이름과 사용 방법. 해당한다면 스테로이드 사용 이력도 알립니다.", "질문: 제게 필요한 검사와 해석 기준, 추가로 확인할 원인, 치료 목표와 재평가 시점은 무엇인가요?"], claimIds: ["OP-B2-003", "OP-B2-005", "OP-B2-011"], sourceIds: ["SRC-NIAMS-OP-TREATMENT", "SRC-NIAMS-OP", "SRC-ISCD-ADULT-POSITIONS"], imageId: null, links: [{ href: "/health/tools/osteoporosis-appointment-prep", label: "골다공증 진료 준비표" }, { href: "/health/guides/medication-list", label: "복용약·보충제 목록 작성하기" }] },
      { title: "뼈 건강 관리와 넘어짐 예방을 나누어 준비하기", paragraphs: ["뼈 건강을 위한 치료와 넘어질 가능성을 줄이는 생활 점검은 함께 필요합니다. 운동은 근력·균형과 일상 기능에 도움이 되지만, 기존 골절이나 몸 상태에 맞는 종류와 범위를 의료진·재활 전문가와 정합니다. 뼈에 갑작스럽거나 과도한 충격을 주는 운동을 누구에게나 권하지 않습니다."], table: { caption: "두 가지 목표에 맞춰 준비할 일", columns: ["목표", "함께 확인할 것", "나에게 맞게 물을 질문"], rows: [["뼈 건강과 골절 위험 관리", "검사·골절 이력, 식사, 약과 보충제, 활동 계획", "제게 필요한 치료·영양·활동의 우선순위는 무엇인가요?"], ["넘어질 위험 줄이기", "통로의 물건·전선, 미끄러운 바닥, 밤 조명, 신발, 균형·시력 변화", "집에서 먼저 바꿀 환경과 진료에 알릴 변화는 무엇인가요?"]] }, claimIds: ["OP-B2-006", "OP-B2-007", "OP-B2-010", "OP-B2-012"], sourceIds: ["SRC-NIAMS-OP-TREATMENT", "SRC-KDCA-OP"], imageId: "op-action", links: [{ href: "/health/tools/osteoporosis-home-check", label: "낙상 위험 집안 점검표" }] },
      { title: "약·보충제와 가족의 도움은 이렇게 상의하세요", paragraphs: ["칼슘·비타민D를 포함한 균형 잡힌 영양과 필요할 때의 약물 치료는 역할이 다릅니다. 보충제 하나나 집안 점검만으로 모든 골절을 막을 수는 없습니다. 약의 선택과 기간, 보충 필요량은 개인 상태를 보고 정하며 이 글이나 숫자만으로 스스로 시작·중단·변경하지 않습니다.", "검사값이 좋아졌거나 약 때문에 불편해졌다면 그 사실을 알려 계획을 재평가받습니다. 치과 치료를 앞두고 있다면 골다공증 치료 사실과 약 이름을 알리고 관련 의료진과 상의합니다. 약을 혼자 중단하는 지침은 아닙니다.", "가족은 당사자가 원하는 도움부터 묻고 통로 정리·조명 점검·진료 준비를 함께합니다. 넘어짐을 개인 탓으로 돌리거나 활동을 무조건 제한하지 않습니다. 안전 점검은 골절을 막는다는 보장이나 위험 점수가 아니라 함께 개선할 환경을 찾는 과정입니다."], claimIds: ["OP-B2-006", "OP-B2-007", "OP-B2-010", "OP-B2-012"], sourceIds: ["SRC-NIAMS-OP-TREATMENT", "SRC-KDCA-OP"], imageId: null, links: [{ href: "/health/guides/older-parent-health-organizer", label: "부모님 건강정보를 동의 아래 함께 정리하기" }] },
    ],
    faq: [
      { question: "골다공증 초기에는 어디가 아픈가요?", answer: "골절 전까지 통증을 못 느낄 수 있어 특정 부위의 통증으로 알아내는 병은 아닙니다. 새롭고 심한 등 통증이나 키·자세 변화는 진료에서 확인합니다.", claimIds: ["OP-B2-002", "OP-B2-008"], sourceIds: ["SRC-NIAMS-OP", "SRC-KDCA-OP"] },
      { question: "T점수와 Z점수가 다르면 무엇을 믿어야 하나요?", answer: "비교하는 기준 집단이 달라 서로 다른 값일 수 있습니다. 폐경 여부·나이 등 개인 상황에 맞는 기준으로 해석하며 어느 하나만 골라 스스로 진단하지 않습니다.", claimIds: ["OP-B2-004", "OP-B2-012"], sourceIds: ["SRC-ISCD-ADULT-POSITIONS", "SRC-NIAMS-BMD"] },
      { question: "혈액검사에서 칼슘이 정상이면 뼈도 괜찮나요?", answer: "혈중 칼슘 검사는 뼛속 칼슘량이나 골밀도를 알려 주지 않습니다. 골밀도 검사는 다른 목적의 검사이므로 필요한지 따로 상담합니다.", claimIds: ["OP-B2-004"], sourceIds: ["SRC-MEDLINEPLUS-BLOOD-CALCIUM"] },
      { question: "넘어진 뒤 정신은 또렷한데 다리를 딛지 못하면 기다려도 되나요?", answer: "기다리지 말고 119에 도움을 요청하세요. 낙상 뒤 심한 고관절 통증이나 체중을 싣지 못하는 변화만으로도 응급 평가가 필요할 수 있습니다. 직접 운전하지 않습니다.", claimIds: ["OP-B2-008", "OP-B2-009"], sourceIds: ["SRC-NHS-HIP-FRACTURE"] },
      { question: "칼슘과 비타민D만 먹으면 약은 필요 없나요?", answer: "영양과 골다공증 약은 같은 역할이 아닙니다. 검사·골절 위험·식사·다른 건강 상태에 따라 필요한 조합을 정하므로 보충제로 처방약을 대신하거나 임의로 중단하지 않습니다.", claimIds: ["OP-B2-007"], sourceIds: ["SRC-NIAMS-OP-TREATMENT", "SRC-KDCA-OP"] },
      { question: "골밀도 검사는 모두 같은 간격으로 다시 하나요?", answer: "반복검사의 목적과 간격은 나이, 이전 결과, 치료와 새로운 위험 요인에 따라 달라집니다. 다음 검사 시점과 그 검사로 무엇을 확인할지 진료에서 물어보세요.", claimIds: ["OP-B2-004", "OP-B2-011"], sourceIds: ["SRC-ISCD-ADULT-POSITIONS"] },
    ],
    sourceIds: ["SRC-KDCA-OP", "SRC-NIAMS-OP", "SRC-NIAMS-OP-TREATMENT", "SRC-NIAMS-BMD", "SRC-ISCD-ADULT-POSITIONS", "SRC-MEDLINEPLUS-BLOOD-CALCIUM", "SRC-NHS-HIP-FRACTURE", "SRC-NIAMS-BONE-HEALTH", "SRC-KDCA-CPR"], imageIds: ["op-hero", "op-explainer", "op-action"], toolSlugs: ["osteoporosis-appointment-prep", "osteoporosis-home-check", "osteoporosis-terms"],
  },
};

export const batch2HealthTools: HealthTool[] = [
  { slug: "allergy-trigger-observation", articleSlug: "allergic-rhinitis", title: "알레르기 비염 관찰표", description: "증상·장소·시간을 적되 원인을 판정하지 않는 기록지입니다.", claimIds: ["AR-B2-003", "AR-B2-005", "AR-B2-012"], kind: "log", columns: ["날짜·시작 시각", "장소·활동", "코 증상·지속 시간", "눈·호흡 변화", "수면·일상 영향", "이미 사용한 약·스프레이", "환경 변화·기타 메모"], rows: 12 },
  { slug: "allergy-environment-check", articleSlug: "allergic-rhinitis", title: "환경 변화 관찰 체크", description: "환경을 바꾼 뒤의 흐름을 살피고 개인 효과를 단정하지 않습니다.", claimIds: ["AR-B2-006", "AR-B2-012"], kind: "checklist", fields: ["이미 바꾼 환경과 날짜·함께 달라진 점 (없음·미확인 표시 가능)"], items: ["오늘의 증상과 장소를 적었습니다.", "바꾼 환경이 있다면 날짜를 함께 적었습니다.", "좋아짐·나빠짐을 한 번의 경험으로 확정하지 않았습니다.", "약 시작·변경은 의료진 또는 약사에게 확인합니다."] },
  { slug: "allergy-appointment-questions", articleSlug: "allergic-rhinitis", title: "알레르기 비염 진료 질문 카드", description: "증상 흐름과 검사 필요 여부를 묻기 위한 질문 카드입니다.", claimIds: ["AR-B2-008", "AR-B2-011"], kind: "questions", fields: ["진료에서 먼저 말할 관찰 사례 (시각·장소·코/눈/호흡·수면 영향)", "현재 약·코/눈 제품명과 실제 사용법 (원본 지참·미확인 표시 가능)"], items: ["이 증상 흐름에서 다른 원인이나 검사를 확인할 필요가 있나요?", "검사가 예정되면 현재 제품별로 어떤 준비 사항을 확인해야 하나요?", "이 약·스프레이의 사용법·기간과 불편이 생길 때 문의 기준은 무엇인가요?", "제가 원하는 가족의 기록 도움과 다음 상담 시점은 어떻게 정하면 좋나요?"] },
  { slug: "gerd-symptom-timing-log", articleSlug: "gastroesophageal-reflux-disease", title: "역류 증상·시간 기록표", description: "식사·자세·수면과 불편의 흐름을 적는 관찰표입니다.", claimIds: ["GERD-B2-004", "GERD-B2-011"], kind: "log", columns: ["날짜·증상 시작 시각", "먹고 마신 것·양·시각", "눕기·수면·굽힌 활동", "불편 종류·지속 시간", "삼킴 변화", "이미 사용한 약·시각", "기타 메모"], rows: 12 },
  { slug: "gerd-everyday-patterns", articleSlug: "gastroesophageal-reflux-disease", title: "역류 생활 패턴 관찰 체크", description: "이미 바꾼 일과 관찰 사실을 구분하는 기록표 보조 도구입니다.", claimIds: ["GERD-B2-005", "GERD-B2-011"], kind: "checklist", fields: ["이미 바꾼 일·날짜 / 같은 시기 다른 변화 / 남은 불편 (없음·미확인 가능)"], items: ["식사·자세·증상이 있었던 실제 시각을 기록표에 나누어 적었습니다.", "특정 음식이나 행동 하나를 원인으로 단정하지 않았습니다.", "약의 시작·중단·변경은 온라인 글로 결정하지 않았습니다.", "위의 위험 신호는 다음 예약이나 체크 완료를 기다리지 않는다는 안내를 확인했습니다."] },
  { slug: "gerd-appointment-prep", articleSlug: "gastroesophageal-reflux-disease", title: "위식도역류 진료 준비 카드", description: "증상·약·검사 필요 여부를 묻기 위한 질문 카드입니다.", claimIds: ["GERD-B2-007", "GERD-B2-010", "GERD-B2-012"], kind: "questions", fields: ["먼저 설명할 불편·시각·지속 / 식사·자세 흐름 (기록 원본·미확인 가능)", "현재 약 이름·실제 사용법 / 이전 검사·기관 안내 (있는 자료 지참)"], items: ["이 증상에서 다른 원인이나 합병증을 확인할 필요가 있나요?", "지금 검사가 필요한가요? 한다면 무엇을 확인하며 어떻게 준비하나요?", "가져온 약·일반약의 사용 계획과 불편할 때 문의 기준은 무엇인가요?", "치료·관찰 결과는 언제 다시 확인하며 예약 전에 연락할 변화와 문의처는 무엇인가요?"] },
  { slug: "oa-daily-activity-log", articleSlug: "osteoarthritis", title: "관절 일상 변화 기록표", description: "활동 전후의 관절 변화와 일상 영향을 적는 관찰표입니다.", claimIds: ["OA-B2-004", "OA-B2-011"], kind: "log", columns: ["날짜", "불편한 관절", "활동", "전후 변화", "부종·열감", "수면", "메모"], rows: 12 },
  { slug: "oa-visit-questions", articleSlug: "osteoarthritis", title: "골관절염 진료 질문 카드", description: "원인 확인과 개인별 활동·치료 선택을 묻기 위한 질문 카드입니다.", claimIds: ["OA-B2-003", "OA-B2-005", "OA-B2-010"], kind: "questions", items: ["이 증상에 다른 원인을 확인할 검사가 필요한가요?", "제 기록에서 어떤 패턴을 봐야 하나요?", "제게 안전한 활동 조정은 무엇인가요?", "약·보조기구·재활 선택은 어떻게 함께 정하나요?"] },
  { slug: "oa-family-support", articleSlug: "osteoarthritis", title: "관절 불편 가족 지원 체크", description: "속도를 재촉하지 않고 일상 지원과 질문 준비를 돕는 체크리스트입니다.", claimIds: ["OA-B2-009", "OA-B2-010"], kind: "checklist", items: ["당사자가 원하는 도움을 먼저 물었습니다.", "통증을 평가하거나 활동을 재촉하지 않았습니다.", "기록과 진료 질문을 함께 정리했습니다.", "약·주사·보조기구를 대신 결정하지 않았습니다."] },
  { slug: "osteoporosis-appointment-prep", articleSlug: "osteoporosis", title: "골다공증 진료 준비표", description: "골절·낙상·복용 약과 검사 질문을 정리하는 준비표입니다.", claimIds: ["OP-B2-004", "OP-B2-005", "OP-B2-011"], kind: "questions", items: ["골밀도 검사가 필요한지와 결과 의미는 무엇인가요?", "낙상·골절·가족력 중 무엇을 알려야 하나요?", "현재 복용 약이 뼈 건강에 미칠 점이 있나요?", "개인에게 맞는 예방·치료 계획은 어떻게 정하나요?"] },
  { slug: "osteoporosis-home-check", articleSlug: "osteoporosis", title: "낙상 위험 집안 점검표", description: "통로와 조명을 점검하되 골절 예방을 보장하지 않는 체크리스트입니다.", claimIds: ["OP-B2-006", "OP-B2-010", "OP-B2-012"], kind: "checklist", items: ["통로에 걸릴 수 있는 물건이 없는지 살폈습니다.", "느슨한 매트나 전선을 확인했습니다.", "밤에 이동하는 길의 조명을 확인했습니다.", "점검표만으로 골절 위험을 계산하거나 보장하지 않았습니다."] },
  { slug: "osteoporosis-terms", articleSlug: "osteoporosis", title: "골밀도 검사 용어 한 장", description: "골밀도 검사와 결과 해석의 경계를 구분하는 안내입니다.", claimIds: ["OP-B2-001", "OP-B2-004", "OP-B2-012"], kind: "guide", items: ["골밀도: 뼈 안의 미네랄 양을 측정하는 검사 정보", "DXA: 골밀도를 재는 데 흔히 쓰이는 검사", "검사 숫자는 나이와 다른 위험 요인을 함께 봐야 함", "한 번의 숫자로 이 페이지에서 진단·약 결정·골절 위험 계산을 하지 않음"] },
];
