-- Draft only. Do not apply automatically.
-- Server-side route handlers insert with SUPABASE_SERVICE_ROLE_KEY when configured.
-- Public anon/client access is intentionally not granted here.

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  topic text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'subscribed',
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.newsletter_subscribers enable row level security;

create table if not exists public.template_download_events (
  id bigint generated by default as identity primary key,
  email text,
  template_key text not null,
  source_path text,
  created_at timestamptz not null default now()
);

alter table public.template_download_events enable row level security;

create table if not exists public.internal_link_click_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type in (
      'related_post',
      'template_cta',
      'next_step',
      'category_hub',
      'contact_cta',
      'search_result'
    )
  ),
  source_path text not null,
  target_path text not null,
  created_at timestamptz not null default now()
);

alter table public.internal_link_click_events enable row level security;

create table if not exists public.post_view_events (
  id bigint generated by default as identity primary key,
  post_slug text not null,
  source_path text,
  created_at timestamptz not null default now()
);

alter table public.post_view_events enable row level security;

-- Future private tables are documented under docs/* and are intentionally not
-- created in MVP code:
-- research_sources, source_snapshots, crawl_jobs, content_evidence,
-- image_assets, content_chunks, content_embeddings, user_queries,
-- ai_answer_logs, product_content_blocks.
