-- Draft only. One-time migration: an existing table must fail rather than hide schema drift.
-- Do not apply to Production without the separate schema and privacy gate.
-- Server-side service-role writes only. No public or authenticated-user table grants.
create table public.commercial_submissions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('inquiry', 'email_lead')),
  service text not null check (service in ('mybiz', 'web', 'minz-mind')),
  email text not null,
  name text,
  message text,
  source text not null,
  landing_url text not null,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  consented_at timestamptz not null,
  created_at timestamptz not null default now(),
  check ((kind = 'inquiry' and name is not null and message is not null)
    or (kind = 'email_lead' and name is null and message is null))
);

create index commercial_submissions_repeat_lookup_idx
  on public.commercial_submissions (service, kind, email, created_at desc);

alter table public.commercial_submissions enable row level security;
revoke all on public.commercial_submissions from anon, authenticated;
revoke all on sequence public.commercial_submissions_id_seq from anon, authenticated;
grant select, insert, delete on public.commercial_submissions to service_role;
grant usage, select on sequence public.commercial_submissions_id_seq to service_role;
