-- Draft only. Do not apply to Production without the separate schema and privacy gate.
-- Server-side service-role writes only. No public or authenticated-user table grants.
create table if not exists public.commercial_submissions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('inquiry', 'email_lead')),
  service text not null check (service in ('mybiz', 'web', 'minz-mind')),
  email text not null,
  name text,
  message text,
  source text not null,
  landing_url text not null,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  consented_at timestamptz not null,
  created_at timestamptz not null default now(),
  check ((kind = 'inquiry' and name is not null and message is not null)
    or (kind = 'email_lead' and name is null and message is null))
);

alter table public.commercial_submissions enable row level security;
revoke all on public.commercial_submissions from anon, authenticated;
