import type { CategorySlug } from "@/lib/schema";

export type ArticleImageConcept = {
  slug: string;
  category: Exclude<CategorySlug, "pillar">;
  visualFamily: string;
  conceptKo: string;
  altKo: string;
  captionKo: string;
  labels: readonly [string, string, string, string];
  palette: {
    accent: string;
    deep: string;
    soft: string;
    warm: string;
    paper: string;
  };
  retainedPremium?: boolean;
};

const automationPalette = {
  accent: "#0f766e",
  deep: "#102a43",
  soft: "#d8f3ee",
  warm: "#f59e0b",
  paper: "#f8fafc",
} as const;

const salesPalette = {
  accent: "#2563eb",
  deep: "#172554",
  soft: "#dbeafe",
  warm: "#14b8a6",
  paper: "#f8fafc",
} as const;

const smallBusinessPalette = {
  accent: "#047857",
  deep: "#1f2937",
  soft: "#d1fae5",
  warm: "#f97316",
  paper: "#fbfdf8",
} as const;

const contractPalette = {
  accent: "#334155",
  deep: "#0f172a",
  soft: "#e2e8f0",
  warm: "#0d9488",
  paper: "#f8fafc",
} as const;

export const articleImageConcepts: Record<string, ArticleImageConcept> = {
  "ai-business-automation-guide": {
    slug: "ai-business-automation-guide",
    category: "automation",
    visualFamily: "automation-orchestration-map",
    conceptKo: "반복 업무, 판단 업무, 기록 업무가 사람 검토와 연결되는 자동화 설계 지도",
    altKo: "반복 업무와 판단 업무를 분리해 사람 검토와 연결한 AI 자동화 설계 지도",
    captionKo: "반복 업무, 기록 업무, 검토 업무를 구분해 안전한 자동화 흐름으로 연결한 이미지입니다.",
    labels: ["반복", "판단", "기록", "검토"],
    palette: automationPalette,
    retainedPremium: true,
  },
  "automation-priority-method": {
    slug: "automation-priority-method",
    category: "automation",
    visualFamily: "priority-matrix",
    conceptKo: "업무 후보 목록을 점수표와 우선순위 매트릭스로 옮기는 장면",
    altKo: "업무 후보를 반복 빈도와 실패 비용으로 나누는 자동화 우선순위 매트릭스",
    captionKo: "업무 후보를 점수화해 먼저 자동화할 항목과 보류할 항목을 나누는 이미지입니다.",
    labels: ["빈도", "위험", "효과", "대기"],
    palette: automationPalette,
  },
  "chatgpt-document-cleanup": {
    slug: "chatgpt-document-cleanup",
    category: "automation",
    visualFamily: "document-cleanup-board",
    conceptKo: "회의 메모, 고객 요청, 보고 초안이 정리된 문서 보드로 바뀌는 장면",
    altKo: "흩어진 회의 메모와 고객 요청을 정리된 업무 문서로 바꾸는 문서 정리 보드",
    captionKo: "메모와 요청을 입력으로 모아 검토 가능한 문서 초안으로 정리하는 이미지입니다.",
    labels: ["메모", "요청", "초안", "정리"],
    palette: automationPalette,
  },
  "google-sheets-ai-automation": {
    slug: "google-sheets-ai-automation",
    category: "automation",
    visualFamily: "spreadsheet-ai-panel",
    conceptKo: "스프레드시트 상태 열과 AI 요약 패널, 알림 카드가 함께 보이는 화면",
    altKo: "스프레드시트 상태 열에서 AI 요약과 알림 패널로 이어지는 자동화 구조",
    captionKo: "표준화된 시트 입력값이 요약, 알림, 담당자 확인으로 이어지는 이미지입니다.",
    labels: ["상태", "요약", "알림", "확인"],
    palette: automationPalette,
  },
  "obsidian-business-knowledge-base": {
    slug: "obsidian-business-knowledge-base",
    category: "automation",
    visualFamily: "knowledge-graph",
    conceptKo: "업무 기준 노트, 고객 응대 노트, 반복 질문 노트가 연결된 지식 그래프",
    altKo: "업무 기준과 고객 응대 노트가 서로 연결된 회사 지식창고 그래프",
    captionKo: "업무 기준, 고객 응대, 반복 질문을 연결해 찾기 쉽게 만든 지식창고 이미지입니다.",
    labels: ["기준", "응대", "질문", "연결"],
    palette: automationPalette,
  },
  "opencut-free-open-source-video-editor-ai-content-automation": {
    slug: "opencut-free-open-source-video-editor-ai-content-automation",
    category: "automation",
    visualFamily: "video-automation-pipeline",
    conceptKo: "상품 정보와 전단형 소재가 쇼츠 템플릿, 자막, 썸네일, 블로그/SNS 패키지로 이어지는 콘텐츠 자동화 파이프라인",
    altKo: "OpenCut 무료 오픈소스 영상 편집기를 AI 콘텐츠 자동화 관점에서 분석한 대표 이미지",
    captionKo: "OpenCut을 단순 무료 편집툴이 아니라 상품 정보와 쇼츠 제작을 연결하는 자동화 후보 도구로 분석한 이미지입니다.",
    labels: ["소재", "쇼츠", "자막", "패키지"],
    palette: automationPalette,
  },
  "free-open-source-automation-tools-series": {
    slug: "free-open-source-automation-tools-series",
    category: "automation",
    visualFamily: "open-source-automation-map",
    conceptKo: "무료 자동화 도구를 콘텐츠, 업무, 데이터 자산화 흐름으로 연결하는 Biz2Lab 도구 지도",
    altKo: "무료 오픈소스 자동화 도구 지도를 Biz2Lab과 MyBiz 업무 흐름 관점에서 정리한 대표 이미지",
    captionKo: "무료 자동화 도구를 콘텐츠, 업무, 데이터 자산화 흐름으로 연결해 보는 Biz2Lab 시리즈 대표 이미지입니다.",
    labels: ["콘텐츠", "업무", "데이터", "자산화"],
    palette: automationPalette,
  },
  "activepieces-ai-business-automation-n8n-alternative": {
    slug: "activepieces-ai-business-automation-n8n-alternative",
    category: "automation",
    visualFamily: "ai-workflow-builder",
    conceptKo: "trigger에서 action으로 이어지는 AI 업무 자동화와 MCP 연결 흐름",
    altKo: "Activepieces를 AI 업무 자동화와 n8n 대안 관점에서 분석한 대표 이미지",
    captionKo: "Activepieces를 문의, 블로그, 쇼츠 요청, 데이터 흐름을 연결하는 AI 업무 자동화 후보로 분석한 이미지입니다.",
    labels: ["trigger", "AI", "MCP", "action"],
    palette: automationPalette,
  },
  "node-red-local-business-automation-server": {
    slug: "node-red-local-business-automation-server",
    category: "automation",
    visualFamily: "local-automation-flow-map",
    conceptKo: "회사 PC와 로컬 서버에서 파일, API, 일정, 알림, 리포트 흐름이 연결되는 자동화 지도",
    altKo: "Node-RED를 로컬 서버 업무 자동화 관점에서 분석한 대표 이미지",
    captionKo: "Node-RED를 회사 PC와 로컬 서버의 이벤트 흐름을 연결하는 자동화 후보로 분석한 이미지입니다.",
    labels: ["파일", "API", "일정", "리포트"],
    palette: automationPalette,
  },
  "baserow-open-source-database-automation": {
    slug: "baserow-open-source-database-automation",
    category: "automation",
    visualFamily: "business-database-automation-board",
    conceptKo: "스프레드시트형 업무 DB, 콘텐츠 캘린더, 상품 데이터, 고객 문의 보드, 자동화 연결선과 승인 게이트가 정돈된 데이터 레이어 지도",
    altKo: "Baserow를 업무 데이터베이스 자동화 관점에서 분석한 대표 이미지",
    captionKo: "Baserow는 고객, 상품, 콘텐츠 데이터를 자동화 파이프라인에 넘기는 데이터 레이어 후보로 볼 수 있다.",
    labels: ["DB", "콘텐츠", "상품", "승인"],
    palette: automationPalette,
  },
  "huginn-monitoring-automation-agent": {
    slug: "huginn-monitoring-automation-agent",
    category: "automation",
    visualFamily: "monitoring-agent-map",
    conceptKo: "웹 페이지 변화, RSS, 가격 카드, 이벤트 에이전트, 승인 게이트가 연결된 업무 모니터링 자동화 지도",
    altKo: "Huginn을 웹 모니터링 자동화 에이전트 관점에서 분석한 대표 이미지",
    captionKo: "Huginn은 웹 변화와 이벤트를 수집해 콘텐츠와 업무 자동화 소재로 넘기는 후보 도구다.",
    labels: ["웹", "RSS", "가격", "승인"],
    palette: automationPalette,
  },
  "pre-automation-task-list": {
    slug: "pre-automation-task-list",
    category: "automation",
    visualFamily: "readiness-checklist",
    conceptKo: "자동화 전 입력 원본, 예외, 고객 영향, 실행 범위를 점검하는 체크리스트",
    altKo: "자동화 전에 입력 원본과 예외 상황을 확인하는 준비 체크리스트",
    captionKo: "입력 자료, 예외 상황, 고객 영향 범위를 먼저 점검하는 이미지입니다.",
    labels: ["원본", "예외", "영향", "범위"],
    palette: automationPalette,
  },
  "reduce-repetitive-work-with-ai": {
    slug: "reduce-repetitive-work-with-ai",
    category: "automation",
    visualFamily: "reduction-kanban",
    conceptKo: "반복 업무 카드가 수집, 분류, 초안, 승인 칸반을 거쳐 줄어드는 장면",
    altKo: "반복 업무를 수집하고 분류해 AI 초안과 사람 승인으로 줄이는 칸반 보드",
    captionKo: "반복 업무를 줄이는 과정을 칸반 보드와 승인 흐름으로 표현한 이미지입니다.",
    labels: ["수집", "분류", "초안", "승인"],
    palette: automationPalette,
  },
  "connect-contract-payment-customer-management": {
    slug: "connect-contract-payment-customer-management",
    category: "contracts-payments",
    visualFamily: "contract-payment-loop",
    conceptKo: "계약, 결제, 거래처 후속 조치가 끊기지 않고 순환하는 운영 흐름",
    altKo: "계약서 작성과 결제 확인, 거래처 후속 조치를 하나로 연결한 운영 흐름",
    captionKo: "계약 상태와 결제 확인, 거래처 후속 조치를 같은 흐름으로 연결한 이미지입니다.",
    labels: ["계약", "결제", "거래처", "후속"],
    palette: contractPalette,
  },
  "e-signature-identity-check": {
    slug: "e-signature-identity-check",
    category: "contracts-payments",
    visualFamily: "identity-signature-split",
    conceptKo: "전자서명 절차와 본인확인 절차를 좌우로 나란히 비교하는 구성",
    altKo: "전자서명과 본인확인 절차를 나란히 비교한 계약 업무 흐름",
    captionKo: "서명 요청과 본인확인 기록이 다른 역할을 한다는 점을 비교한 이미지입니다.",
    labels: ["서명", "확인", "기록", "완료"],
    palette: contractPalette,
  },
  "electronic-contract-system-basics": {
    slug: "electronic-contract-system-basics",
    category: "contracts-payments",
    visualFamily: "contract-status-timeline",
    conceptKo: "초안, 서명 요청, 본인확인, 보관으로 이어지는 전자계약 상태 타임라인",
    altKo: "전자계약의 초안 작성부터 서명 요청과 보관까지 이어지는 상태 타임라인",
    captionKo: "전자계약 시스템의 기본 상태를 시간 흐름으로 정리한 이미지입니다.",
    labels: ["초안", "요청", "확인", "보관"],
    palette: contractPalette,
    retainedPremium: true,
  },
  "manage-unsigned-contracts": {
    slug: "manage-unsigned-contracts",
    category: "contracts-payments",
    visualFamily: "unsigned-follow-up-board",
    conceptKo: "미작성 계약 목록과 담당자 확인, 재안내 일정이 함께 있는 후속 조치 보드",
    altKo: "미작성 계약 목록을 사유와 담당자, 재안내 일정으로 관리하는 후속 조치 보드",
    captionKo: "서명이 멈춘 거래처를 사유, 담당자, 다음 안내일로 추적하는 이미지입니다.",
    labels: ["미작성", "사유", "담당", "재안내"],
    palette: contractPalette,
  },
  "offline-card-payment-pg-van": {
    slug: "offline-card-payment-pg-van",
    category: "contracts-payments",
    visualFamily: "pg-van-settlement-map",
    conceptKo: "카드 키인 결제, PG, VAN, 정산 표가 분리되어 연결된 결제 확인 지도",
    altKo: "카드 키인 결제와 PG, VAN, 정산 확인 흐름을 구분한 결제 지도",
    captionKo: "결제 입력, 승인 경로, 정산 확인을 구분해 보는 이미지입니다.",
    labels: ["키인", "PG", "VAN", "정산"],
    palette: contractPalette,
  },
  "accounts-receivable-tracker": {
    slug: "accounts-receivable-tracker",
    category: "sales-ops",
    visualFamily: "receivable-aging-board",
    conceptKo: "미수금 aging 구간과 약속일, 담당자 후속 조치가 보이는 회수 상태판",
    altKo: "미수금 aging 구간과 약속일, 담당자 후속 조치를 함께 보여주는 회수 상태판",
    captionKo: "미수금 상태를 경과일과 다음 연락 기준으로 나누어 보는 이미지입니다.",
    labels: ["0-7", "8-30", "31+", "연락"],
    palette: salesPalette,
    retainedPremium: true,
  },
  "daily-sales-goal-breakdown": {
    slug: "daily-sales-goal-breakdown",
    category: "sales-ops",
    visualFamily: "sales-goal-chart",
    conceptKo: "월 목표가 일 목표와 현재 매출, 잔여 목표 대시보드로 나뉘는 장면",
    altKo: "월 매출 목표를 일일 목표와 현재 매출, 잔여 목표로 나눈 대시보드",
    captionKo: "월 목표를 매일 확인할 숫자와 남은 행동량으로 나누는 이미지입니다.",
    labels: ["월목표", "일목표", "현재", "잔여"],
    palette: salesPalette,
  },
  "daily-sales-report": {
    slug: "daily-sales-report",
    category: "sales-ops",
    visualFamily: "daily-report-dashboard",
    conceptKo: "실적, 상담, 견적, 다음 행동을 한 장에 모은 일일 영업 보고 화면",
    altKo: "실적과 상담, 견적, 다음 행동을 한 화면에 정리한 영업팀 일일 보고서",
    captionKo: "하루 영업 활동을 짧은 지표와 다음 행동으로 정리한 이미지입니다.",
    labels: ["실적", "상담", "견적", "다음"],
    palette: salesPalette,
  },
  "payment-reminder-message": {
    slug: "payment-reminder-message",
    category: "sales-ops",
    visualFamily: "reminder-approval-flow",
    conceptKo: "부드러운 입금 안내문 초안이 검토와 승인 후 발송 대기열로 이동하는 흐름",
    altKo: "거래처 독촉 문자와 입금 안내문 초안을 검토하고 승인 후 발송하는 메시지 승인 흐름",
    captionKo: "거래처 안내문을 초안, 검토, 승인, 발송 단계로 나누어 표현한 이미지입니다.",
    labels: ["초안", "검토", "승인", "발송"],
    palette: salesPalette,
  },
  "sales-achievement-rate": {
    slug: "sales-achievement-rate",
    category: "sales-ops",
    visualFamily: "achievement-gauge",
    conceptKo: "목표 대비 실적 게이지와 부족분, 필요한 행동량이 함께 보이는 화면",
    altKo: "목표 대비 실적 게이지와 부족분, 필요한 행동량을 보여주는 매출 달성률 화면",
    captionKo: "현재 실적과 부족분을 행동 기준으로 바꾸어 보는 이미지입니다.",
    labels: ["목표", "실적", "부족", "행동"],
    palette: salesPalette,
  },
  "sales-revenue-ar-structure": {
    slug: "sales-revenue-ar-structure",
    category: "sales-ops",
    visualFamily: "revenue-ar-map",
    conceptKo: "매출, 청구, 입금, 대기 상태가 하나의 흐름으로 이어지는 영업 관리 지도",
    altKo: "매출 목표와 청구, 입금, 미수금 대기 상태를 연결한 영업관리 지도",
    captionKo: "매출과 미수금을 분리하지 않고 한 흐름으로 확인하는 이미지입니다.",
    labels: ["매출", "청구", "입금", "대기"],
    palette: salesPalette,
  },
  "unify-order-channels-for-sales": {
    slug: "unify-order-channels-for-sales",
    category: "sales-ops",
    visualFamily: "order-channel-funnel",
    conceptKo: "전화, 메일, 현장 요청이 하나의 거래처 주문 보드로 모이는 영업 운영 흐름",
    altKo: "전화와 메일, 현장 요청을 하나의 거래처 주문 보드로 모으는 흐름",
    captionKo: "흩어진 거래처 주문 채널을 한 기준의 주문 보드로 통합한 이미지입니다.",
    labels: ["전화", "메일", "현장", "주문"],
    palette: salesPalette,
  },
  "ai-knowledge-store-for-small-business": {
    slug: "ai-knowledge-store-for-small-business",
    category: "small-business",
    visualFamily: "ai-store-knowledge-card",
    conceptKo: "운영 기준, 메뉴 기준, 고객 질문이 AI 점장 답변 기준으로 연결된 카드",
    altKo: "운영 기준과 고객 질문을 AI 점장 답변 기준으로 연결한 소상공인 지식 카드",
    captionKo: "AI 점장이 참고할 운영 기준과 고객 질문을 한곳에 모은 이미지입니다.",
    labels: ["운영", "메뉴", "질문", "답변"],
    palette: smallBusinessPalette,
  },
  "customer-memory-system": {
    slug: "customer-memory-system",
    category: "small-business",
    visualFamily: "customer-record-card",
    conceptKo: "고객 요청, 선호, 이전 응대, 다음 조치가 정리된 고객 기록 카드",
    altKo: "고객 요청과 선호, 응대 이력, 다음 조치를 정리한 고객 기록 카드",
    captionKo: "고객별 요청과 이전 응대 이력을 다음 조치로 연결한 이미지입니다.",
    labels: ["요청", "선호", "이력", "다음"],
    palette: smallBusinessPalette,
  },
  "daily-numbers-for-small-business": {
    slug: "daily-numbers-for-small-business",
    category: "small-business",
    visualFamily: "daily-numbers-dashboard",
    conceptKo: "매출, 주문 수, 객단가, 재방문, 미처리 업무를 보는 일일 숫자 대시보드",
    altKo: "소상공인이 매일 확인할 매출 달성률 계산과 주문, 입금, 미처리 업무 대시보드",
    captionKo: "하루 운영 상태를 다섯 가지 숫자로 확인하는 이미지입니다.",
    labels: ["매출", "주문", "객단가", "미처리"],
    palette: smallBusinessPalette,
  },
  "reservation-order-review-management": {
    slug: "reservation-order-review-management",
    category: "small-business",
    visualFamily: "service-triage-board",
    conceptKo: "예약, 주문, 리뷰 응대가 같은 운영표에서 상태별로 정리된 보드",
    altKo: "예약과 주문, 리뷰 응대를 같은 운영표에서 상태별로 관리하는 보드",
    captionKo: "예약, 주문, 리뷰를 각각의 다음 행동과 함께 정리한 이미지입니다.",
    labels: ["예약", "주문", "리뷰", "응대"],
    palette: smallBusinessPalette,
  },
  "solo-business-systemization": {
    slug: "solo-business-systemization",
    category: "small-business",
    visualFamily: "solo-system-loop",
    conceptKo: "상담, 주문, 정산, 고객 기록이 작은 업무 시스템으로 순환하는 장면",
    altKo: "1인 사업자의 상담과 주문, 정산, 고객 기록이 순환하는 업무 시스템",
    captionKo: "혼자 처리하는 업무를 반복 가능한 시스템으로 묶어 보여주는 이미지입니다.",
    labels: ["상담", "주문", "정산", "기록"],
    palette: smallBusinessPalette,
  },
  "unify-order-channels": {
    slug: "unify-order-channels",
    category: "small-business",
    visualFamily: "restaurant-order-pipeline",
    conceptKo: "전화, 메신저, 플랫폼 주문이 접수와 처리 상태판으로 모이는 매장 주문 흐름",
    altKo: "전화와 메신저, 플랫폼 주문을 한곳의 처리 상태판으로 모으는 매장 주문 흐름",
    captionKo: "흩어진 주문을 접수, 준비, 완료 상태로 정리한 이미지입니다.",
    labels: ["전화", "메신저", "플랫폼", "처리"],
    palette: smallBusinessPalette,
  },
  "appsmith-internal-dashboard-automation": {
    slug: "appsmith-internal-dashboard-automation",
    category: "automation",
    visualFamily: "internal-dashboard-builder",
    conceptKo: "운영자가 보는 내부 대시보드, 작업 승인 카드, 데이터 소스 연결, 자동화 로그가 정돈된 고급 업무형 히어로 이미지.",
    altKo: "Appsmith를 내부 관리자 화면 자동화 관점에서 분석한 대표 이미지",
    captionKo: "Appsmith는 자동화 결과를 사람이 검토하고 승인하는 내부 운영 화면 후보로 볼 수 있다.",
    labels: ["internal dashboard", "approval cards", "data source", "automation log"],
    palette: automationPalette,
  },
  "windmill-developer-workflow-automation": {
    slug: "windmill-developer-workflow-automation",
    category: "automation",
    visualFamily: "developer-workflow-control-room",
    conceptKo: "코드 스크립트, 워크플로 타임라인, 내부 앱 패널, 실행 로그, 승인 게이트가 결합된 업무 자동화 컨트롤룸 이미지.",
    altKo: "Windmill을 개발자용 업무 자동화 관점에서 분석한 대표 이미지",
    captionKo: "Windmill은 스크립트와 워크플로를 묶어 내부 자동화를 실행하는 개발자형 후보 도구다.",
    labels: ["script runner", "workflow timeline", "internal app panel", "execution log"],
    palette: automationPalette,
  },
  "kestra-data-ai-workflow-orchestration": {
    slug: "kestra-data-ai-workflow-orchestration",
    category: "automation",
    visualFamily: "data-ai-orchestration-map",
    conceptKo: "데이터 파이프라인, AI 작업, 콘텐츠 생성, 리포트, 실행 이력이 중앙 오케스트레이터로 연결된 고급 업무 자동화 히어로 이미지.",
    altKo: "Kestra를 데이터와 AI 워크플로 오케스트레이션 관점에서 분석한 대표 이미지",
    captionKo: "Kestra는 여러 자동화 흐름이 커졌을 때 중앙에서 실행과 이력을 관리하는 후보 도구다.",
    labels: ["workflow orchestration", "data pipeline", "AI task", "content output"],
    palette: automationPalette,
  },
  "n8n-workflow-automation-license-caution": {
    slug: "n8n-workflow-automation-license-caution",
    category: "automation",
    visualFamily: "workflow-license-check-map",
    conceptKo: "워크플로 노드, 라이선스 체크포인트, self-hosted 서버, 업무 승인 게이트가 함께 보이는 고급 업무 자동화 검토 이미지.",
    altKo: "n8n을 워크플로 자동화와 라이선스 주의 관점에서 분석한 대표 이미지",
    captionKo: "n8n은 자동화 흐름을 연결하는 후보지만, 업무 적용 전 라이선스와 self-hosted 사용 범위를 확인해야 한다.",
    labels: ["workflow nodes", "license checkpoint", "self-hosted server", "approval gate"],
    palette: automationPalette,
  },
  "nocodb-airtable-alternative-license-caution": {
    slug: "nocodb-airtable-alternative-license-caution",
    category: "automation",
    visualFamily: "database-license-comparison-board",
    conceptKo: "데이터베이스 그리드, Airtable 대체 후보 비교, 라이선스 확인 카드, 백업과 권한 게이트가 있는 업무 자동화 이미지.",
    altKo: "NocoDB를 Airtable 대체 데이터베이스와 라이선스 주의 관점에서 분석한 대표 이미지",
    captionKo: "NocoDB는 업무 데이터베이스 후보지만, Baserow와 비교해 라이선스와 운영 범위를 따로 확인해야 한다.",
    labels: ["database grid", "comparison board", "license caution card", "backup gate"],
    palette: automationPalette,
  },
  "crawl4ai-blog-research-automation": {
    slug: "crawl4ai-blog-research-automation",
    category: "automation",
    visualFamily: "ethical-research-crawler-map",
    conceptKo: "공개 웹 문서, robots 체크, rate limit 게이트, 리서치 큐, 사람이 검토하는 승인 보드가 연결된 안전한 AI 리서치 자동화 이미지.",
    altKo: "Crawl4AI를 블로그 리서치 자동화와 안전한 크롤링 게이트 관점에서 분석한 대표 이미지",
    captionKo: "Crawl4AI는 콘텐츠 리서치 후보지만 robots, 약관, rate limit, 출처 검토를 먼저 통과해야 한다.",
    labels: ["public web documents", "robots check", "rate limit gate", "research queue"],
    palette: automationPalette,
  },
  "langflow-ai-workflow-automation": {
    slug: "langflow-ai-workflow-automation",
    category: "automation",
    visualFamily: "llm-flow-builder-operations-map",
    conceptKo: "시각적 LLM 워크플로 캔버스, 프롬프트 체인, 콘텐츠 큐, 사람 승인 게이트, 배포 주의 표시가 연결된 AI 자동화 운영 이미지.",
    altKo: "Langflow로 AI 워크플로와 LLM 앱 제작 흐름을 검토하는 대표 이미지",
    captionKo: "Langflow는 LLM 앱 프로토타입을 만들 수 있는 후보지만 라이선스와 배포 조건 확인이 먼저다.",
    labels: ["visual workflow canvas", "LLM prompt chain", "content queue", "human approval gate"],
    palette: automationPalette,
  },
  "dify-llm-app-builder-business-automation": {
    slug: "dify-llm-app-builder-business-automation",
    category: "automation",
    visualFamily: "llm-assistant-rag-workflow-board",
    conceptKo: "챗봇 워크플로, RAG 지식 베이스, assistant 검토 큐, 운영자 승인, self-host 주의 표시가 있는 AI 앱 빌더 이미지.",
    altKo: "Dify로 LLM 앱과 RAG assistant 운영 흐름을 검토하는 대표 이미지",
    captionKo: "Dify는 챗봇과 RAG 워크플로 후보지만 cloud, self-hosting, 데이터 조건 확인이 필요하다.",
    labels: ["chatbot workflow", "RAG knowledge base", "assistant review queue", "operator approval"],
    palette: automationPalette,
  },
  "open-webui-local-llm-admin-portal": {
    slug: "open-webui-local-llm-admin-portal",
    category: "automation",
    visualFamily: "local-llm-internal-portal-control-room",
    conceptKo: "로컬 LLM 포털, 모델 접근 제어, 팀 지식 assistant, privacy gate, admin log가 보이는 내부 AI 운영 이미지.",
    altKo: "Open WebUI로 로컬 LLM 내부 AI 포털 운영을 검토하는 대표 이미지",
    captionKo: "Open WebUI는 내부 AI 포털 후보지만 모델 접근 제어와 프라이버시 게이트가 필요하다.",
    labels: ["local LLM portal", "model access control", "team knowledge assistant", "privacy gate"],
    palette: automationPalette,
  },
  "flowise-ai-agent-workflow-automation": {
    slug: "flowise-ai-agent-workflow-automation",
    category: "automation",
    visualFamily: "ai-agent-flow-safety-dashboard",
    conceptKo: "AI 에이전트 flow 캔버스, tool permission gate, chatflow prototype, stability checklist, human review가 있는 안전 대시보드 이미지.",
    altKo: "Flowise로 AI 에이전트 워크플로와 안전 게이트를 검토하는 대표 이미지",
    captionKo: "Flowise는 agent flow 프로토타입 후보지만 production 안정성과 권한 검토가 먼저다.",
    labels: ["agent workflow canvas", "tool permission gate", "chatflow prototype", "stability checklist"],
    palette: automationPalette,
  },
  "directus-headless-cms-data-automation": {
    slug: "directus-headless-cms-data-automation",
    category: "automation",
    visualFamily: "headless-cms-data-portal-map",
    conceptKo: "Headless CMS data model, internal admin portal, API gate, permission matrix, backup checklist가 연결된 데이터 운영 이미지.",
    altKo: "Directus로 headless CMS와 데이터 운영 포털을 검토하는 대표 이미지",
    captionKo: "Directus는 데이터 운영 layer 후보지만 권한, 백업, cloud/self-host 조건 확인이 필요하다.",
    labels: ["headless CMS data model", "internal admin portal", "API gate", "permission matrix"],
    palette: automationPalette,
  },
  "pocketbase-lightweight-backend-saas-mvp": {
    slug: "pocketbase-lightweight-backend-saas-mvp",
    category: "automation",
    visualFamily: "lightweight-backend-mvp-operations-map",
    conceptKo: "Lightweight backend, auth module, database module, file storage, backup and scaling gate가 있는 SaaS MVP 운영 이미지.",
    altKo: "PocketBase로 소규모 SaaS MVP 백엔드 운영을 검토하는 대표 이미지",
    captionKo: "PocketBase는 MVP backend 후보지만 backup과 scaling gate가 필요하다.",
    labels: ["lightweight backend", "auth module", "database module", "file storage"],
    palette: automationPalette,
  },
  "supabase-self-hosting-cost-operations-caution": {
    slug: "supabase-self-hosting-cost-operations-caution",
    category: "automation",
    visualFamily: "self-hosted-backend-cost-operations-balance",
    conceptKo: "Managed cloud와 self-hosting 저울, Postgres operations, Auth and Storage cards, backup gate, hidden cost chart가 있는 backend 운영 이미지.",
    altKo: "Supabase self-hosting의 비용과 운영 부담을 비교하는 대표 이미지",
    captionKo: "Supabase self-hosting은 비용뿐 아니라 Postgres, Auth, Storage 운영 책임을 함께 계산해야 한다.",
    labels: ["managed vs self-hosting balance", "Postgres operations", "Auth and Storage cards", "backup gate"],
    palette: automationPalette,
  },
  "meilisearch-blog-product-search-automation": {
    slug: "meilisearch-blog-product-search-automation",
    category: "automation",
    visualFamily: "search-index-automation-dashboard",
    conceptKo: "Search index pipeline, blog and product cards, search result panel, indexing schedule, hosting operations gate가 있는 검색 자동화 이미지.",
    altKo: "Meilisearch로 블로그와 상품 검색 index 자동화를 검토하는 대표 이미지",
    captionKo: "Meilisearch는 검색 자동화 후보지만 index 운영과 hosting 조건 확인이 필요하다.",
    labels: ["search index pipeline", "blog and product cards", "search result panel", "indexing schedule"],
    palette: automationPalette,
  },
  "typesense-product-document-search-automation": {
    slug: "typesense-product-document-search-automation",
    category: "automation",
    visualFamily: "search-api-catalog-document-control-board",
    conceptKo: "Search API panel, catalog and document index, comparison board, permission filter, reindex checklist가 있는 검색 운영 이미지.",
    altKo: "Typesense로 상품과 문서 검색 API 자동화를 검토하는 대표 이미지",
    captionKo: "Typesense는 search API 후보지만 권한 필터와 reindex 운영 설계가 필요하다.",
    labels: ["search API panel", "catalog and document index", "comparison board", "permission filter"],
    palette: automationPalette,
  },
  "umami-open-source-analytics-ga-alternative": {
    slug: "umami-open-source-analytics-ga-alternative",
    category: "automation",
    visualFamily: "privacy-analytics-dashboard-operations-map",
    conceptKo: "Privacy-friendly analytics dashboard, blog traffic metrics, GA alternative comparison, hosting choice, data ownership gate가 있는 웹 분석 운영 이미지.",
    altKo: "Umami로 GA 대체 웹 분석과 privacy 운영을 검토하는 대표 이미지",
    captionKo: "Umami는 analytics 후보지만 privacy, hosting, consent 조건 확인이 필요하다.",
    labels: ["privacy analytics dashboard", "blog traffic metrics", "GA alternative comparison", "hosting choice"],
    palette: automationPalette,
  },
  "plausible-open-source-analytics-ga-alternative": {
    slug: "plausible-open-source-analytics-ga-alternative",
    category: "automation",
    visualFamily: "privacy-analytics-dashboard-operations-map",
    conceptKo: "Privacy-friendly analytics dashboard, lightweight blog traffic metrics, GA alternative comparison, consent gate, hosting choice, data ownership map in a premium Biz2Lab editorial hero.",
    altKo: "Plausible을 GA 대체 웹 분석과 개인정보 보호 관점에서 검토하는 대표 이미지",
    captionKo: "Plausible은 가벼운 웹 분석 후보이지만 privacy, hosting, consent 조건을 함께 확인해야 합니다.",
    labels: ["privacy analytics dashboard", "lightweight traffic metrics", "GA alternative comparison", "consent gate"],
    palette: automationPalette,
  },
  "matomo-self-hosted-analytics-privacy-caution": {
    slug: "matomo-self-hosted-analytics-privacy-caution",
    category: "automation",
    visualFamily: "self-hosted-privacy-analytics-control-room",
    conceptKo: "Self-hosted analytics control room, privacy checklist, cookie consent gate, data retention board, server operations status in a premium Biz2Lab editorial hero.",
    altKo: "Matomo 셀프호스팅 웹 분석을 개인정보와 운영 리스크 관점에서 검토하는 대표 이미지",
    captionKo: "Matomo는 분석 통제권을 넓힐 수 있지만 privacy와 self-hosting 운영 책임을 함께 확인해야 합니다.",
    labels: ["self-hosted analytics control room", "privacy checklist", "cookie consent gate", "data retention board"],
    palette: automationPalette,
  },
  "posthog-product-analytics-automation": {
    slug: "posthog-product-analytics-automation",
    category: "automation",
    visualFamily: "product-analytics-event-automation-map",
    conceptKo: "Product analytics event pipeline, funnel board, feature flag cards, approval gate, privacy retention checklist in a premium Biz2Lab editorial hero.",
    altKo: "PostHog 제품 분석과 이벤트 자동화 흐름을 개인정보 리스크와 함께 검토하는 대표 이미지",
    captionKo: "PostHog는 제품 이벤트 분석 후보이지만 event taxonomy, privacy, retention 기준을 먼저 설계해야 합니다.",
    labels: ["product analytics event pipeline", "funnel board", "feature flag cards", "approval gate"],
    palette: automationPalette,
  },
  "metabase-dashboard-automation-for-small-business": {
    slug: "metabase-dashboard-automation-for-small-business",
    category: "automation",
    visualFamily: "small-business-dashboard-control-room",
    conceptKo: "소상공인 운영 대시보드, 매출/주문/미수금/검색 지표 카드, 데이터 연결 게이트, 권한 관리 패널이 있는 프리미엄 Biz2Lab 에디토리얼 히어로.",
    altKo: "Metabase로 소상공인 업무 대시보드 자동화를 검토하는 Biz2Lab 분석 이미지",
    captionKo: "Metabase는 쉬운 대시보드 후보이지만 데이터 원본, 권한, 공유 기준을 먼저 정해야 합니다.",
    labels: ["small business dashboard", "sales and orders metrics", "receivables card", "search performance panel"],
    palette: automationPalette,
  },
  "apache-superset-bi-dashboard-automation": {
    slug: "apache-superset-bi-dashboard-automation",
    category: "automation",
    visualFamily: "bi-dashboard-automation-command-center",
    conceptKo: "BI 대시보드 자동화 커맨드 센터, 차트 그리드, 데이터 모델 계층, 권한 게이트, 리포트 자동화 흐름이 있는 프리미엄 Biz2Lab 히어로.",
    altKo: "Apache Superset으로 BI 대시보드 자동화를 검토하는 Biz2Lab 분석 이미지",
    captionKo: "Apache Superset은 강한 BI 후보이지만 데이터 모델과 운영 권한 기준을 먼저 정해야 합니다.",
    labels: ["BI dashboard", "chart grid", "data model layer", "permission gate"],
    palette: automationPalette,
  },
  "redash-open-source-dashboard-automation": {
    slug: "redash-open-source-dashboard-automation",
    category: "automation",
    visualFamily: "sql-reporting-dashboard-automation-map",
    conceptKo: "SQL 리포팅 대시보드, 반복 질의 카드, 내부 보고 흐름, 권한 게이트, 운영 지표 보드가 있는 프리미엄 Biz2Lab 에디토리얼 히어로.",
    altKo: "Redash로 SQL 리포팅 대시보드 자동화를 검토하는 Biz2Lab 분석 이미지",
    captionKo: "Redash는 SQL 리포팅 후보이지만 프로젝트 상태와 권한, 공유 기준 확인이 먼저입니다.",
    labels: ["SQL reporting dashboard", "query cards", "internal report flow", "permission gate"],
    palette: automationPalette,
  },
};

export const articleImageConceptEntries: ArticleImageConcept[] = Object.values(articleImageConcepts);

export const premiumArticleImageSlugs = articleImageConceptEntries
  .filter((concept) => concept.retainedPremium)
  .map((concept) => concept.slug);

export function getArticleImageConcept(slug: string) {
  return articleImageConcepts[slug];
}
