import type { ArticleImageConcept } from "@/lib/article-image-concepts";

const watchPalette = {
  accent: "#ef5b3f",
  deep: "#3b1f4a",
  soft: "#fff0e5",
  warm: "#f7c948",
  paper: "#fffdf9",
} as const;

const creditsPalette = {
  accent: "#7c3aed",
  deep: "#2f1747",
  soft: "#f1e8ff",
  warm: "#f97316",
  paper: "#fffdf9",
} as const;

const streamingPalette = {
  accent: "#0f766e",
  deep: "#193b45",
  soft: "#dff7f2",
  warm: "#f59e0b",
  paper: "#fffdf9",
} as const;

export const entertainmentImageConcepts = {
  "devil-wears-prada-ending-interpretation": {
    slug: "devil-wears-prada-ending-interpretation",
    category: "after-the-credits",
    visualFamily: "fashion-office-crossroads",
    conceptKo: "구두와 엘리베이터, 열린 거리로 야망과 경계선의 선택을 표현한 오리지널 편집 이미지",
    altKo: "악마는 프라다를 입는다의 앤디와 미란다를 야망과 경계선의 관점에서 해석하는 편집 노트",
    captionKo: "일과 야망을 버리는 장면이 아니라 자신의 경계선을 다시 선택하는 순간을 상징적으로 표현했습니다.",
    labels: ["야망", "경계", "선택", "방향"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "her-ai-relationship-interpretation": {
    slug: "her-ai-relationship-interpretation",
    category: "after-the-credits",
    visualFamily: "voice-and-empty-room",
    conceptKo: "이어피스와 목소리 파형, 빈 의자로 연결과 외로움, 이별 뒤의 성장을 표현한 오리지널 편집 이미지",
    altKo: "영화 Her의 목소리 기반 관계와 마지막 이별을 외로움과 성장의 관점에서 해석하는 편집 노트",
    captionKo: "목소리로 이어진 관계와 그 관계가 사라진 뒤 남는 외로움과 성장을 상징적으로 표현했습니다.",
    labels: ["목소리", "연결", "외로움", "성장"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "inside-out-2-emotions-interpretation": {
    slug: "inside-out-2-emotions-interpretation",
    category: "after-the-credits",
    visualFamily: "anxiety-emotion-spiral",
    conceptKo: "감정 구체와 커지는 주황색 나선으로 보호하려는 불안이 통제권을 차지하는 과정을 표현한 추상 이미지",
    altKo: "인사이드 아웃 2의 불안과 기존 감정들이 라일리의 선택을 두고 충돌하는 장면을 분석하는 편집 노트",
    captionKo: "라일리를 지키려는 불안이 다른 감정을 밀어내는 과정을 저작권 캐릭터 없이 추상적으로 표현했습니다.",
    labels: ["불안", "보호", "통제", "균형"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "inside-out-emotion-interpretation": {
    slug: "inside-out-emotion-interpretation",
    category: "after-the-credits",
    visualFamily: "memory-orb-bridge",
    conceptKo: "노란색과 파란색 기억 구체가 다리를 건너는 모습으로 슬픔이 연결과 회복을 돕는 과정을 표현한 추상 이미지",
    altKo: "인사이드 아웃의 기쁨과 슬픔이 함께 기억을 다루는 장면을 해석하는 편집 노트",
    captionKo: "기쁨만으로 해결되지 않는 기억을 슬픔이 연결과 회복으로 바꾸는 과정을 추상적으로 표현했습니다.",
    labels: ["기쁨", "슬픔", "기억", "연결"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "lalaland-ending-interpretation": {
    slug: "lalaland-ending-interpretation",
    category: "after-the-credits",
    visualFamily: "jazz-stage-diverging-paths",
    conceptKo: "빈 재즈 무대와 잠시 겹쳤다가 갈라지는 두 길로 사랑과 선택을 표현한 오리지널 편집 이미지",
    altKo: "라라랜드의 재즈 클럽과 마지막 상상 몽타주를 사랑과 선택의 관점에서 해석하는 편집 노트",
    captionKo: "함께하지 못한 사랑을 실패가 아니라 서로의 선택과 감사로 남기는 결말을 상징적으로 표현했습니다.",
    labels: ["사랑", "선택", "꿈", "감사"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "parasite-ending-interpretation": {
    slug: "parasite-ending-interpretation",
    category: "after-the-credits",
    visualFamily: "class-staircase-cutaway",
    conceptKo: "저택과 반지하를 잇는 계단, 닿기 어려운 빛으로 계층 이동과 마지막 계획의 거리를 표현한 건축 이미지",
    altKo: "영화 기생충의 반지하와 저택을 잇는 계단과 마지막 계획을 분석하는 편집 노트",
    captionKo: "계단과 높이의 차이를 통해 마지막 계획이 품은 희망과 구조적 한계를 상징적으로 표현했습니다.",
    labels: ["계단", "반지하", "계획", "거리"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "the-intern-work-and-age-interpretation": {
    slug: "the-intern-work-and-age-interpretation",
    category: "after-the-credits",
    visualFamily: "shared-desk-generations",
    conceptKo: "낡은 서류가방과 현대적 노트북이 놓인 공동 책상으로 세대를 넘어선 존중과 협업을 표현한 이미지",
    altKo: "영화 인턴의 벤과 줄스를 해결사와 대표가 아닌 좋은 동료의 관계로 해석하는 편집 노트",
    captionKo: "한 사람이 다른 사람을 구하는 관계보다 서로의 속도와 경험을 존중하는 동료 관계를 표현했습니다.",
    labels: ["경험", "존중", "동료", "협업"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "truman-show-ending-interpretation": {
    slug: "truman-show-ending-interpretation",
    category: "after-the-credits",
    visualFamily: "sailboat-exit-door",
    conceptKo: "인공 하늘 끝의 범선과 빛나는 출구로 자유를 선택하는 용기와 불확실성을 표현한 오리지널 이미지",
    altKo: "트루먼 쇼의 인공 바다 끝에 놓인 출구와 선택의 의미를 해석하는 편집 노트",
    captionKo: "문 너머가 완벽해서가 아니라 모르는 세계를 스스로 선택한다는 결말의 의미를 표현했습니다.",
    labels: ["바다", "출구", "자유", "선택"],
    palette: creditsPalette,
    retainedPremium: true,
  },
  "family-profile-age-rating": {
    slug: "family-profile-age-rating",
    category: "streaming-life",
    visualFamily: "family-profile-safety-screen",
    conceptKo: "가족 프로필 카드와 방패, 차단 카드를 이용해 연령등급과 작품 제한을 보여주는 생활형 이미지",
    altKo: "가족 구성원별 넷플릭스 프로필과 연령등급과 작품 차단을 설정하는 안내",
    captionKo: "프로필마다 연령등급과 작품 차단을 따로 적용하는 흐름을 브랜드 화면 복제 없이 표현했습니다.",
    labels: ["프로필", "연령", "차단", "보호"],
    palette: streamingPalette,
    retainedPremium: true,
  },
  "netflix-profile-reset-recommendations": {
    slug: "netflix-profile-reset-recommendations",
    category: "streaming-life",
    visualFamily: "recommendation-reset-loop",
    conceptKo: "프로필과 시청 흔적, 평가 토큰을 순서대로 재정렬하는 추천 정리 흐름 이미지",
    altKo: "넷플릭스 프로필과 시청기록과 평가를 순서대로 정리해 추천 화면을 다시 맞추는 안내",
    captionKo: "프로필, 기록, 평가를 차례대로 정리해 추천 화면을 다시 맞추는 과정을 추상적으로 표현했습니다.",
    labels: ["프로필", "기록", "평가", "추천"],
    palette: streamingPalette,
    retainedPremium: true,
  },
  "netflix-subtitle-settings": {
    slug: "netflix-subtitle-settings",
    category: "streaming-life",
    visualFamily: "cross-device-subtitle-controls",
    conceptKo: "TV와 모바일, 자막 줄과 크기 조절 장치로 기기별 자막 설정을 표현한 접근성 이미지",
    altKo: "TV와 모바일에서 넷플릭스 자막 언어와 크기와 음성을 조정하는 설정 안내",
    captionKo: "기기마다 다르게 보이는 자막과 음성 설정을 화면 복제 없이 이해하기 쉽게 표현했습니다.",
    labels: ["TV", "모바일", "자막", "음성"],
    palette: streamingPalette,
    retainedPremium: true,
  },
  "netflix-viewing-history-delete": {
    slug: "netflix-viewing-history-delete",
    category: "streaming-life",
    visualFamily: "viewing-history-fade",
    conceptKo: "영화 카드가 시청 타임라인에서 사라지고 추천 목록이 재배열되는 과정을 표현한 이미지",
    altKo: "넷플릭스 계정의 시청 활동에서 작품을 숨기고 추천 변화를 확인하는 설정 안내",
    captionKo: "시청 활동에서 작품을 숨겼을 때 기록과 추천 화면이 달라지는 흐름을 추상적으로 표현했습니다.",
    labels: ["기록", "숨김", "추천", "변화"],
    palette: streamingPalette,
    retainedPremium: true,
  },
  "ott-subscription-rotation": {
    slug: "ott-subscription-rotation",
    category: "streaming-life",
    visualFamily: "annual-subscription-wheel",
    conceptKo: "열두 달 원형 달력과 순환하는 서비스 토큰으로 OTT 구독을 한 달씩 운영하는 방법을 표현한 이미지",
    altKo: "여러 OTT 서비스를 시청 월에 맞춰 하나씩 순환하며 연간 비용을 확인하는 구독 관리표",
    captionKo: "여러 OTT를 동시에 유지하지 않고 보고 싶은 달에 하나씩 순환하는 구독 관리 방식을 표현했습니다.",
    labels: ["달력", "순환", "구독", "비용"],
    palette: streamingPalette,
    retainedPremium: true,
  },
  "watchlist-without-spoilers": {
    slug: "watchlist-without-spoilers",
    category: "streaming-life",
    visualFamily: "five-slot-watchlist-board",
    conceptKo: "기분과 이유, 러닝타임 등을 다섯 칸으로 나눈 스포일러 없는 관람 목록 이미지",
    altKo: "영화 줄거리 스포일러 없이 이유와 기분과 러닝타임만 기록한 다섯 칸 관람 목록",
    captionKo: "줄거리 대신 보고 싶은 이유와 기분, 러닝타임을 기록하는 다섯 칸 목록을 표현했습니다.",
    labels: ["이유", "기분", "시간", "다음"],
    palette: streamingPalette,
    retainedPremium: true,
  },
  "date-night-movie-guide": {
    slug: "date-night-movie-guide",
    category: "what-to-watch",
    visualFamily: "two-seat-shared-choice",
    conceptKo: "서로 다른 두 좌석과 취향 토큰이 한 화면 앞에서 만나는 데이트 영화 선택 이미지",
    altKo: "취향이 다른 두 사람이 분위기와 대화거리를 기준으로 데이트 영화를 고르는 모습",
    captionKo: "취향이 다른 두 사람이 한쪽의 양보가 아니라 공통 분위기와 대화거리를 찾는 과정을 표현했습니다.",
    labels: ["취향", "분위기", "대화", "선택"],
    palette: watchPalette,
    retainedPremium: true,
  },
  "family-movie-night-guide": {
    slug: "family-movie-night-guide",
    category: "what-to-watch",
    visualFamily: "family-viewing-agreement",
    conceptKo: "서로 다른 크기의 쿠션과 자막, 공포 강도, 합의 토큰으로 가족 관람 기준을 표현한 이미지",
    altKo: "서로 다른 연령의 가족이 무서운 장면과 자막 여부를 확인하며 영화를 고르는 모습",
    captionKo: "나이만으로 정하지 않고 무서운 장면과 자막 여부를 함께 합의하는 가족 영화 선택을 표현했습니다.",
    labels: ["가족", "자막", "강도", "합의"],
    palette: watchPalette,
    retainedPremium: true,
  },
  "horror-movie-intensity-guide": {
    slug: "horror-movie-intensity-guide",
    category: "what-to-watch",
    visualFamily: "three-door-horror-dials",
    conceptKo: "세 개의 문과 조절 다이얼로 점프스케어, 잔혹함, 심리 불안의 강도를 표현한 이미지",
    altKo: "공포영화의 놀람과 잔혹함과 심리 불안을 서로 다른 강도로 비교하는 선택표",
    captionKo: "공포영화의 서로 다른 불편 요소를 잔혹한 묘사 없이 세 가지 강도 축으로 표현했습니다.",
    labels: ["놀람", "잔혹함", "불안", "강도"],
    palette: watchPalette,
    retainedPremium: true,
  },
  "netflix-top-10-how-to-choose": {
    slug: "netflix-top-10-how-to-choose",
    category: "what-to-watch",
    visualFamily: "ranking-versus-taste-compass",
    conceptKo: "인기 순위 탑과 취향 나침반을 나란히 놓아 순위와 개인 추천의 차이를 보여주는 이미지",
    altKo: "넷플릭스 인기 순위와 개인 취향 조건을 나란히 비교해 한 작품을 고르는 화면",
    captionKo: "인기 순위와 개인의 기분, 장르, 러닝타임 조건이 서로 다른 선택 기준임을 표현했습니다.",
    labels: ["순위", "취향", "기분", "선택"],
    palette: watchPalette,
    retainedPremium: true,
  },
  "ninety-minute-movie-guide": {
    slug: "ninety-minute-movie-guide",
    category: "what-to-watch",
    visualFamily: "compact-runtime-clock",
    conceptKo: "한 시간 반을 가리키는 원형 시계와 세 장의 영화 티켓으로 짧고 완결된 관람을 표현한 이미지",
    altKo: "90분 타이머와 영화 후보 세 편을 비교하는 간결한 관람 선택 화면",
    captionKo: "짧은 러닝타임 안에서도 충분한 완결감과 여운을 주는 작품 선택을 표현했습니다.",
    labels: ["90분", "후보", "완결", "여운"],
    palette: watchPalette,
    retainedPremium: true,
  },
  "rewatch-or-new-movie": {
    slug: "rewatch-or-new-movie",
    category: "what-to-watch",
    visualFamily: "familiar-versus-new-reel",
    conceptKo: "익숙한 필름과 새 필름 사이에서 에너지 토큰으로 선택하는 장면을 표현한 이미지",
    altKo: "익숙한 영화와 새로운 영화 사이에서 오늘의 에너지를 기준으로 선택하는 장면",
    captionKo: "다시 보기와 새 작품 사이의 선택을 취향보다 오늘 남은 에너지의 문제로 표현했습니다.",
    labels: ["익숙함", "새로움", "에너지", "선택"],
    palette: watchPalette,
    retainedPremium: true,
  },
  "theater-or-ott-choice": {
    slug: "theater-or-ott-choice",
    category: "what-to-watch",
    visualFamily: "cinema-home-split-world",
    conceptKo: "영화관 좌석과 편안한 거실을 나란히 놓고 일곱 선택 기준을 연결한 비교 이미지",
    altKo: "큰 스크린의 영화관과 편안한 거실 OTT 환경을 일곱 가지 기준으로 비교하는 장면",
    captionKo: "영화관과 OTT 중 어느 쪽이 우월한지가 아니라 오늘의 조건에 맞는 환경을 비교해 표현했습니다.",
    labels: ["화면", "소리", "시간", "비용"],
    palette: watchPalette,
    retainedPremium: true,
  },
  "tired-after-work-movie-guide": {
    slug: "tired-after-work-movie-guide",
    category: "what-to-watch",
    visualFamily: "after-work-cozy-choice",
    conceptKo: "노을이 드는 거실과 시계, 영화 카드로 피곤한 저녁의 관람 선택을 표현한 이미지",
    altKo: "피곤한 저녁 소파에서 남은 시간과 기분에 맞는 영화를 고르는 장면",
    captionKo: "퇴근 후 남은 시간과 에너지를 먼저 확인하고 부담 없는 영화를 고르는 순간을 표현했습니다.",
    labels: ["피로", "시간", "기분", "선택"],
    palette: watchPalette,
    retainedPremium: true,
  },
} as const satisfies Record<string, ArticleImageConcept>;
