-- Canonical one-time Biz2Lab Commercial migration.
-- Production application requires separate Owner approval and exact target verification.
-- MyBiz owns the shared project's existing public/core/private objects.
-- Biz2Lab data is isolated in its own non-exposed schema. Public contains only
-- narrowly named service-role RPC entrypoints so the shared Data API exposed
-- schema configuration does not need to change.

create schema biz2lab;

revoke all on schema biz2lab from public, anon, authenticated, service_role;

create table biz2lab.commercial_submissions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('inquiry', 'email_lead')),
  service text not null check (service in ('mybiz', 'web', 'minz-mind')),
  email text not null,
  name text,
  message text,
  source text not null,
  landing_url text not null,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  consented_at timestamptz not null,
  created_at timestamptz not null default now(),
  check ((kind = 'inquiry' and name is not null and message is not null)
    or (kind = 'email_lead' and name is null and message is null))
);

create index commercial_submissions_repeat_lookup_idx
  on biz2lab.commercial_submissions (service, kind, email, created_at desc);

create unique index commercial_submissions_atomic_dedupe_idx
  on biz2lab.commercial_submissions (
    service, kind, email,
    (date_bin('10 minutes'::interval, created_at, '2000-01-01 00:00:00+00'::timestamptz))
  );

alter table biz2lab.commercial_submissions enable row level security;

-- Defense in depth: the table and identity sequence are not directly available
-- to Data API roles, including service_role. Server access is through the
-- service-role-only RPCs below.
revoke all on table biz2lab.commercial_submissions from public, anon, authenticated, service_role;
revoke all on sequence biz2lab.commercial_submissions_id_seq from public, anon, authenticated, service_role;

create function public.biz2lab_commercial_recent_submission_exists(
  p_service text,
  p_kind text,
  p_email text,
  p_cutoff timestamptz
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from biz2lab.commercial_submissions s
    where s.service = p_service
      and s.kind = p_kind
      and s.email = lower(p_email)
      and s.created_at >= p_cutoff
  );
$$;

create function public.biz2lab_commercial_insert_submission(
  p_kind text,
  p_service text,
  p_email text,
  p_name text,
  p_message text,
  p_source text,
  p_landing_url text,
  p_utm_source text,
  p_utm_medium text,
  p_utm_campaign text,
  p_consented_at timestamptz,
  p_created_at timestamptz default now()
)
returns bigint
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  insert into biz2lab.commercial_submissions (
    kind, service, email, name, message, source, landing_url,
    utm_source, utm_medium, utm_campaign, consented_at, created_at
  )
  values (
    p_kind, p_service, lower(p_email), p_name, p_message, p_source, p_landing_url,
    p_utm_source, p_utm_medium, p_utm_campaign, p_consented_at, p_created_at
  )
  returning id into v_id;
  return v_id;
end;
$$;

create function public.biz2lab_commercial_rows_by_email(p_email text)
returns table (
  id bigint,
  kind text,
  service text,
  email text,
  name text,
  message text,
  source text,
  landing_url text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  consented_at timestamptz,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    s.id, s.kind, s.service, s.email, s.name, s.message, s.source,
    s.landing_url, s.utm_source, s.utm_medium, s.utm_campaign,
    s.consented_at, s.created_at
  from biz2lab.commercial_submissions s
  where s.email = lower(p_email)
  order by s.id;
$$;

create function public.biz2lab_commercial_expired_ids(p_cutoff timestamptz)
returns table (id bigint)
language sql
stable
security definer
set search_path = ''
as $$
  select s.id
  from biz2lab.commercial_submissions s
  where s.created_at < p_cutoff
  order by s.id;
$$;

create function public.biz2lab_commercial_delete_submission(p_id bigint)
returns boolean
language sql
volatile
security definer
set search_path = ''
as $$
  with deleted as (
    delete from biz2lab.commercial_submissions
    where id = p_id
    returning 1
  )
  select exists(select 1 from deleted);
$$;

revoke all on function public.biz2lab_commercial_recent_submission_exists(text,text,text,timestamptz)
  from public, anon, authenticated, service_role;
revoke all on function public.biz2lab_commercial_insert_submission(
  text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz
) from public, anon, authenticated, service_role;
revoke all on function public.biz2lab_commercial_rows_by_email(text)
  from public, anon, authenticated, service_role;
revoke all on function public.biz2lab_commercial_expired_ids(timestamptz)
  from public, anon, authenticated, service_role;
revoke all on function public.biz2lab_commercial_delete_submission(bigint)
  from public, anon, authenticated, service_role;

grant execute on function public.biz2lab_commercial_recent_submission_exists(text,text,text,timestamptz)
  to service_role;
grant execute on function public.biz2lab_commercial_insert_submission(
  text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz
) to service_role;
grant execute on function public.biz2lab_commercial_rows_by_email(text)
  to service_role;
grant execute on function public.biz2lab_commercial_expired_ids(timestamptz)
  to service_role;
grant execute on function public.biz2lab_commercial_delete_submission(bigint)
  to service_role;
